const sampleRoutesTableData = {
    totalPages: 10,
    totalDocuments: 100,
    data: [
        {
            path: "/api/v1/institutes/owners/register",
            type: "PLATFORM",
            description: "Handles institute owner registration and email verification.",
            isPublic: true,
            method: "GET",
            name: "Register Institute Owner",
        },
        {
            path: "/api/v1/institutes/current-onboarded-user",
            type: "PLATFORM",
            description: "Retrieves details of the currently onboarded institute owner.",
            isPublic: true,
            method: "GET",
            name: "Fetch Onboarded User",
        },
        {
            path: "/api/v1/institutes/owners/verify",
            type: "PLATFORM",
            description: "Verifies the institute owner's email address.",
            isPublic: true,
            method: "POST",
            name: "Verify Institute Owner",
        },
        {
            path: "/api/v1/institutes/setup/basic-info",
            type: "PLATFORM",
            description: "Collects and stores basic information about the institute.",
            isPublic: false,
            method: "POST",
            name: "Setup Basic Info",
        },
        {
            path: "/api/v1/institutes/setup/details",
            type: "PLATFORM",
            description: "Configures full details of the institute, including structure and policies.",
            isPublic: false,
            method: "POST",
            name: "Setup Institute Details",
        },
        {
            path: "/api/v1/institutes/setup/template",
            type: "PLATFORM",
            description: "Sets up the institute's operational templates and workflows.",
            isPublic: false,
            method: "POST",
            name: "Configure Institute Template",
        },
        {
            path: "/api/v1/institutes/setup/payment",
            type: "PLATFORM",
            description: "Configures payment options and billing details for the institute.",
            isPublic: false,
            method: "POST",
            name: "Setup Payment",
        },
        {
            path: "/api/v1/institutes/brand/logo/upload",
            type: "PLATFORM",
            description: "Allows institutes to upload and manage their brand logo for platform visibility.",
            isPublic: false,
            method: "POST",
            name: "Upload Brand Logo",
        },
        {
            path: "/api/v1/institutes/owners/documents/identity-proof/upload",
            type: "PLATFORM",
            description: "Allows institute owners to securely upload identity proof documents for verification.",
            isPublic: false,
            method: "POST",
            name: "Upload Identity Proof",
        },
        {
            path: "/api/v1/privilege-group",
            type: "PLATFORM",
            description: "Creates a new privilege group",
            isPublic: false,
            method: "POST",
            name: "Create Privilege Group",
        },
        {
            path: "/api/v1/privilege-group",
            type: "PLATFORM",
            description: "Retrieves a list of all privilege groups",
            isPublic: false,
            method: "GET",
            name: "Get Privilege Groups",
        },
        {
            path: "/api/v1/health",
            type: "CLIENT",
            description: "No description provided",
            isPublic: false,
            method: "GET",
            name: "Unnamed Route",
        },
    ],
};

export default sampleRoutesTableData;
