const sampleSubscriptionsTableData = {
  totalPages: 3,
  totalDocuments: 8,
  records: [
    {
      id: "1",
      name: "Basic Monthly Access",
      planType: "TIERED",
      description: "Perfect for beginners starting their learning journey",
      price: 19900,
      originalPrice: 29900,
      currency: "INR",
      billingCycle: {
        duration: 30,
        unit: "DAY",
      },
      accessType: "ALL_FEATURES",
      metadata: {
        isPopular: false,
        hasCertificate: true,
        badge: "Best for Beginners",
        tags: ["basic", "monthly", "certificate"],
      },
      trial: {
        isTrialAvailable: false,
      },
      isActive: true,
      features: ["Access to 5 courses", "Basic support", "Mobile app access"],
      courses: ["course-react-001", "course-marketing-001"],
      enrollmentCount: 1250,
      growthPercentage: 12.5,
    },
    {
      id: "2",
      name: "Premium Monthly Plan",
      planType: "TIERED",
      description: "Unlimited access to all current and future courses with premium features",
      price: 2999,
      originalPrice: 3999,
      currency: "INR",
      billingCycle: {
        duration: 1,
        unit: "MONTH",
      },
      accessType: "ALL_FEATURES",
      metadata: {
        isPopular: true,
        hasCertificate: true,
        badge: "Best for Serious Learners",
        tags: ["premium", "monthly", "unlimited"],
      },
      trial: {
        isTrialAvailable: true,
        trialPeriod: { duration: 7, unit: "DAY" },
      },
      isActive: true,
      features: [
        "Unlimited Course Access",
        "Priority Support",
        "Certificate Included",
        "Mobile App Access",
        "Offline Content",
      ],
      courses: ["course-react-001", "course-marketing-001", "course-python-001"],
      enrollmentCount: 3250,
      growthPercentage: 18.7,
    },
    {
      id: "3",
      name: "Lifetime Access",
      planType: "LIFETIME_ACCESS",
      description: "One-time payment for lifetime access to all courses",
      price: 99999,
      originalPrice: 129999,
      currency: "INR",
      billingCycle: {
        duration: 1,
        unit: "YEAR",
      },
      accessType: "ALL_FEATURES",
      metadata: {
        isPopular: false,
        hasCertificate: true,
        badge: "Best Value",
        tags: ["lifetime", "unlimited", "premium"],
      },
      trial: {
        isTrialAvailable: false,
      },
      isActive: true,
      features: [
        "Lifetime Course Access",
        "Premium Support",
        "All Future Courses",
        "Certificate Included",
        "Priority Updates",
      ],
      courses: ["course-react-001", "course-marketing-001", "course-python-001", "course-design-001"],
      enrollmentCount: 850,
      growthPercentage: 8.3,
    },
    {
      id: "4",
      name: "Student Plan",
      planType: "TIERED",
      description: "Special discounted plan for students with verification",
      price: 1499,
      originalPrice: 2999,
      currency: "INR",
      billingCycle: {
        duration: 1,
        unit: "MONTH",
      },
      accessType: "ALL_FEATURES",
      metadata: {
        isPopular: false,
        hasCertificate: true,
        badge: "Student Discount",
        tags: ["student", "discount", "monthly"],
      },
      trial: {
        isTrialAvailable: true,
        trialPeriod: { duration: 14, unit: "DAY" },
      },
      isActive: true,
      features: ["Student Discount", "Course Access", "Standard Support", "Certificate Included"],
      courses: ["course-react-001", "course-python-001"],
      enrollmentCount: 2100,
      growthPercentage: 25.4,
    },
    {
      id: "5",
      name: "Enterprise Plan",
      planType: "RECURRING",
      description: "Custom enterprise solution with team management",
      price: 299999,
      originalPrice: null,
      currency: "INR",
      billingCycle: {
        duration: 1,
        unit: "YEAR",
      },
      accessType: "ALL_FEATURES",
      metadata: {
        isPopular: false,
        hasCertificate: true,
        badge: "Enterprise",
        tags: ["enterprise", "team", "custom"],
      },
      trial: {
        isTrialAvailable: true,
        trialPeriod: { duration: 30, unit: "DAY" },
      },
      isActive: true,
      features: [
        "Unlimited Team Access",
        "Advanced Analytics",
        "Custom Branding",
        "Priority Support",
        "Team Management",
      ],
      courses: [
        "course-react-001",
        "course-marketing-001",
        "course-python-001",
        "course-design-001",
        "course-datascience-001",
      ],
      enrollmentCount: 125,
      growthPercentage: 15.2,
    },
    {
      id: "6",
      name: "Exam Only Access",
      planType: "TIERED",
      description: "Access to practice exams and assessments only",
      price: 999,
      originalPrice: null,
      currency: "INR",
      billingCycle: {
        duration: 3,
        unit: "MONTH",
      },
      accessType: "EXAM_ONLY",
      metadata: {
        isPopular: false,
        hasCertificate: false,
        badge: "Exam Prep",
        tags: ["exam", "assessment", "practice"],
      },
      trial: {
        isTrialAvailable: false,
      },
      isActive: true,
      features: ["Practice Exams", "Assessment Tools", "Progress Tracking", "Basic Support"],
      courses: [],
      enrollmentCount: 750,
      growthPercentage: 5.8,
    },
    {
      id: "7",
      name: "Video Only Plan",
      planType: "RECURRING",
      description: "Access to video content only, no additional resources",
      price: 1999,
      originalPrice: 2499,
      currency: "INR",
      billingCycle: {
        duration: 1,
        unit: "MONTH",
      },
      accessType: "VIDEO_ONLY",
      metadata: {
        isPopular: false,
        hasCertificate: false,
        badge: "Video Access",
        tags: ["video", "streaming", "basic"],
      },
      trial: {
        isTrialAvailable: true,
        trialPeriod: { duration: 3, unit: "DAY" },
      },
      isActive: false,
      features: ["Video Streaming", "Mobile Access", "Basic Support"],
      courses: ["course-react-001", "course-marketing-001"],
      enrollmentCount: 450,
      growthPercentage: -2.1,
    },
    {
      id: "8",
      name: "Free Trial Plan",
      planType: "TIERED",
      description: "Free trial access to explore our platform",
      price: 0,
      originalPrice: null,
      currency: "INR",
      billingCycle: {
        duration: 7,
        unit: "DAY",
      },
      accessType: "READ_ONLY_CONTENT",
      metadata: {
        isPopular: false,
        hasCertificate: false,
        badge: "Free Trial",
        tags: ["free", "trial", "limited"],
      },
      trial: {
        isTrialAvailable: true,
        trialPeriod: { duration: 7, unit: "DAY" },
      },
      isActive: true,
      features: ["Limited Course Access", "Basic Support", "7-Day Trial"],
      courses: ["course-react-001"],
      enrollmentCount: 5200,
      growthPercentage: 45.2,
    },
  ],
}

export default sampleSubscriptionsTableData
