const comprehensiveQuestionData = {
    totalPages: 3,
    totalDocuments: 25,
    records: [
        {
            id: "q_001",
            questionId: "MATH_001",
            type: "MCQ",
            text: "What is the value of x in the equation 2x + 5 = 15?",
            image: "",
            options: [
                { id: "a", text: "3", isCorrect: false },
                { id: "b", text: "5", isCorrect: true },
                { id: "c", text: "7", isCorrect: false },
                { id: "d", text: "10", isCorrect: false },
            ],
            answer: { correctOption: "b" },
            tags: ["algebra", "linear-equations", "basic"],
            difficulty: "easy",
            language: "en",
            explanation: "To solve 2x + 5 = 15, subtract 5 from both sides: 2x = 10, then divide by 2: x = 5.",
            category: "Mathematics",
            subject: "Algebra",
            isPublic: true,
            status: "ACTIVE",
        },
        {
            id: "q_002",
            questionId: "SCI_001",
            type: "TRUE_FALSE",
            text: "Photosynthesis occurs in the mitochondria of plant cells.",
            image: "",
            answer: { value: false },
            tags: ["biology", "photosynthesis", "cell-biology"],
            difficulty: "medium",
            language: "en",

            explanation: "Photosynthesis occurs in the chloroplasts, not mitochondria. Mitochondria are responsible for cellular respiration.",
            category: "Science",
            subject: "Biology",
            topic: "Cell Biology",
            isPublic: true,
            status: "ACTIVE",
        },
        {
            id: "q_003",
            questionId: "ENG_001",
            type: "FILL_BLANKS",
            text: "Shakespeare wrote the famous play '______' which features the characters Romeo and Juliet.",
            image: "",
            answer: { text: "Romeo and Juliet", caseSensitive: false },
            tags: ["literature", "shakespeare", "drama"],
            difficulty: "easy",
            language: "en",

            explanation: "Romeo and Juliet is one of Shakespeare's most famous tragedies, written in the early part of his career.",
            category: "English",
            subject: "Literature",
            topic: "Shakespeare",

            isPublic: true,

            status: "ACTIVE",
        },
        {
            id: "q_004",
            questionId: "PHYS_001",
            type: "NUMERIC",
            text: "A ball is dropped from a height of 20 meters. Calculate the time it takes to reach the ground (use g = 9.8 m/s²).",
            image: "",
            answer: { value: 2.02, tolerance: 0.1 },
            tags: ["physics", "kinematics", "gravity"],
            difficulty: "medium",
            language: "en",

            explanation: "Using the equation h = ½gt², we get t = √(2h/g) = √(2×20/9.8) = √4.08 ≈ 2.02 seconds.",
            category: "Physics",
            subject: "Mechanics",
            topic: "Kinematics",

            isPublic: true,

            status: "ACTIVE",
        },
        {
            id: "q_005",
            questionId: "HIST_001",
            type: "ESSAY",
            text: "Analyze the causes and consequences of World War I. Discuss at least three major factors that led to the war and explain how the war changed the global political landscape.",
            image: "",
            answer: {
                sampleAnswer:
                    "World War I was caused by multiple factors including: 1) Imperialism - European powers competing for colonies, 2) Alliance system - complex web of alliances that escalated conflicts, 3) Nationalism - ethnic tensions in the Balkans. The war resulted in the fall of empires (Ottoman, Austro-Hungarian, German, Russian), creation of new nations, and set the stage for World War II.",
                maxWords: 500,
            },
            tags: ["history", "world-war-1", "analysis"],
            difficulty: "hard",
            language: "en",

            explanation: "This question tests understanding of complex historical causation and the ability to analyze long-term consequences.",
            category: "History",
            subject: "World History",
            topic: "20th Century",

            isPublic: false,
            status: "ACTIVE",
        },
        {
            id: "q_006",
            questionId: "CHEM_001",
            type: "MCQ",
            text: "What is the molecular formula for glucose?",
            image: "",
            options: [
                { id: "a", text: "C₆H₁₂O₆", isCorrect: true },
                { id: "b", text: "C₆H₁₀O₅", isCorrect: false },
                { id: "c", text: "C₅H₁₀O₅", isCorrect: false },
                { id: "d", text: "C₆H₁₄O₆", isCorrect: false },
            ],
            answer: { correctOption: "a" },
            tags: ["chemistry", "organic", "carbohydrates"],
            difficulty: "easy",
            language: "en",

            explanation: "Glucose is a simple sugar with the molecular formula C₆H₁₂O₆, containing 6 carbon, 12 hydrogen, and 6 oxygen atoms.",
            category: "Chemistry",
            subject: "Organic Chemistry",
            topic: "Carbohydrates",

            isPublic: true,
            status: "ACTIVE",
        },
        {
            id: "q_007",
            questionId: "GEO_001",
            type: "MULTI_SELECT",
            text: "Which of the following are characteristics of tropical rainforests? (Select all that apply)",
            image: "",
            options: [
                { id: "a", text: "High biodiversity", isCorrect: true },
                { id: "b", text: "Low annual rainfall", isCorrect: false },
                { id: "c", text: "Layered canopy structure", isCorrect: true },
                { id: "d", text: "Extreme temperature variations", isCorrect: false },
                { id: "e", text: "High humidity", isCorrect: true },
                { id: "f", text: "Poor soil quality", isCorrect: true },
            ],
            answer: { correctOptions: ["a", "c", "e", "f"] },
            tags: ["geography", "ecosystems", "rainforest"],
            difficulty: "medium",
            language: "en",
            points: 4,
            timeLimit: 90,
            explanation: "Tropical rainforests are characterized by high biodiversity, layered canopy structure, high humidity, and ironically poor soil quality due to rapid nutrient cycling.",
            category: "Geography",
            subject: "Physical Geography",
            topic: "Ecosystems",
            subtopic: "Tropical Rainforests",
            isPublic: true,
            allowPartialCredit: true,
            status: "ACTIVE",
        },
        {
            id: "q_008",
            questionId: "CS_001",
            type: "MCQ",
            text: "Which data structure follows the Last In, First Out (LIFO) principle?",
            image: "",
            options: [
                { id: "a", text: "Queue", isCorrect: false },
                { id: "b", text: "Stack", isCorrect: true },
                { id: "c", text: "Array", isCorrect: false },
                { id: "d", text: "Linked List", isCorrect: false },
            ],
            answer: { correctOption: "b" },
            tags: ["computer-science", "data-structures", "stack"],
            difficulty: "easy",
            language: "en",

            explanation: "A stack follows the LIFO principle where the last element added is the first one to be removed, like a stack of plates.",
            category: "Computer Science",
            subject: "Data Structures",
            topic: "Linear Data Structures",
            subtopic: "Stack",
            isPublic: true,
            allowPartialCredit: false,
            status: "ACTIVE",
        },
        {
            id: "q_009",
            questionId: "LANG_001",
            type: "FILL_BLANKS",
            text: "The past tense of the verb 'go' is ______.",
            image: "",
            answer: { text: "went", caseSensitive: false },
            tags: ["language", "grammar", "verbs"],
            difficulty: "very_easy",
            language: "en",
            points: 1,
            timeLimit: 20,
            explanation: "'Went' is the irregular past tense form of the verb 'go'.",
            category: "English",
            subject: "Grammar",
            topic: "Verbs",
            isPublic: true,
            status: "ACTIVE",
        },
        {
            id: "q_010",
            questionId: "STAT_001",
            type: "NUMERIC",
            text: "Calculate the mean of the following dataset: 12, 15, 18, 20, 25, 30, 35",
            image: "",
            answer: { value: 22.14, tolerance: 0.1 },
            tags: ["statistics", "mean", "central-tendency"],
            difficulty: "easy",
            language: "en",

            explanation: "Mean = (12+15+18+20+25+30+35) ÷ 7 = 155 ÷ 7 = 22.14",
            category: "Mathematics",
            subject: "Statistics",
            topic: "Descriptive Statistics",
            isPublic: true,
            status: "ACTIVE",
        },
        {
            id: "q_011",
            questionId: "ART_001",
            type: "TRUE_FALSE",
            text: "Leonardo da Vinci painted the Mona Lisa during the Renaissance period.",
            image: "",
            answer: { value: true },
            tags: ["art", "renaissance", "leonardo-da-vinci"],
            difficulty: "easy",
            language: "en",

            explanation: "Leonardo da Vinci painted the Mona Lisa between 1503-1519, which was during the High Renaissance period.",
            category: "Art",
            subject: "Art History",
            topic: "Renaissance Art",
            subtopic: "Italian Renaissance",
            isPublic: true,
            status: "ACTIVE",
        },
        {
            id: "q_012",
            questionId: "ECON_001",
            type: "MCQ",
            text: "What happens to the demand curve when consumer income increases for a normal good?",
            image: "",
            options: [
                { id: "a", text: "Shifts to the left", isCorrect: false },
                { id: "b", text: "Shifts to the right", isCorrect: true },
                { id: "c", text: "Becomes steeper", isCorrect: false },
                { id: "d", text: "Remains unchanged", isCorrect: false },
            ],
            answer: { correctOption: "b" },
            tags: ["economics", "demand", "income-effect"],
            difficulty: "medium",
            language: "en",

            explanation: "For normal goods, an increase in consumer income leads to an increase in demand, shifting the demand curve to the right.",
            category: "Economics",
            subject: "Microeconomics",
            topic: "Demand and Supply",
            isPublic: true,
            status: "ACTIVE",
        },
        {
            id: "q_013",
            questionId: "PSYC_001",
            type: "ESSAY",
            text: "Explain the concept of classical conditioning and provide a real-world example. Discuss how this learning process differs from operant conditioning.",
            image: "",
            answer: {
                sampleAnswer:
                    "Classical conditioning is a learning process where a neutral stimulus becomes associated with a meaningful stimulus, eventually triggering a conditioned response. Example: Pavlov's dogs learned to salivate at the sound of a bell. This differs from operant conditioning, which involves learning through consequences (rewards/punishments) rather than associations.",
                maxWords: 300,
            },
            tags: ["psychology", "learning", "conditioning"],
            difficulty: "medium",
            language: "en",

            explanation: "This question tests understanding of fundamental learning theories in psychology.",
            category: "Psychology",
            subject: "Learning Psychology",
            topic: "Classical Conditioning",
            isPublic: false,
            status: "ACTIVE",
        },
        {
            id: "q_014",
            questionId: "MUS_001",
            type: "MCQ",
            text: "How many strings does a standard guitar have?",
            image: "",
            options: [
                { id: "a", text: "4", isCorrect: false },
                { id: "b", text: "5", isCorrect: false },
                { id: "c", text: "6", isCorrect: true },
                { id: "d", text: "7", isCorrect: false },
            ],
            answer: { correctOption: "c" },
            tags: ["music", "instruments", "guitar"],
            difficulty: "very_easy",
            language: "en",

            explanation: "A standard acoustic or electric guitar has 6 strings, typically tuned to E-A-D-G-B-E from lowest to highest.",
            category: "Music",
            subject: "Music Theory",
            topic: "Instruments",

            isPublic: true,
            status: "ACTIVE",
        },
        {
            id: "q_015",
            questionId: "PHIL_001",
            type: "ESSAY",
            text: "Discuss Plato's Allegory of the Cave and its significance in understanding the nature of reality and knowledge. How does this allegory relate to modern concepts of education and enlightenment?",
            image: "",
            answer: {
                sampleAnswer:
                    "Plato's Allegory of the Cave illustrates the journey from ignorance to knowledge. Prisoners chained in a cave mistake shadows for reality until one escapes and sees the true world. This represents the philosopher's journey from the world of appearances to the world of forms. In modern education, it emphasizes the importance of critical thinking and questioning assumptions to reach deeper understanding.",
                maxWords: 400,
            },
            tags: ["philosophy", "plato", "epistemology"],
            difficulty: "very_hard",
            language: "en",

            explanation: "This question requires deep understanding of philosophical concepts and ability to connect ancient philosophy to modern contexts.",
            category: "Philosophy",
            subject: "Ancient Philosophy",
            topic: "Plato",

            isPublic: false,
            status: "ACTIVE",
        },
    ],
};

export default comprehensiveQuestionData;
