const samplePermissionTableData = {
    totalPages: 10,
    totalDocuments: 100,
    records: [
        {
            id: 1,
            name: "createUser",
            description: "Create a new user",
            permissionGroup: "User Module",
            routes: [{ name: "/user/create" }],
            status: "Active",
            createdAt: "2024-03-02T14:30:00Z",
        },
        {
            id: 2,
            name: "editUser",
            description: "Modify user details",
            permissionGroup: "User Module",
            routes: [{ name: "/user/edit" }],
            status: "Active",
            createdAt: "2024-03-12T14:30:00Z",
        },
        {
            id: 3,
            name: "deleteUser",
            description: "Remove user account",
            permissionGroup: "User Module",
            routes: [{ name: "/user/delete" }],
            status: "Inactive",
            createdAt: "2024-03-10T08:45:00Z",
        },
        {
            id: 4,
            name: "viewUsers",
            description: "List all users",
            permissionGroup: "User Module",
            routes: [{ name: "/user/list" }],
            status: "Active",
            createdAt: "2024-03-09T11:15:00Z",
        },
        {
            id: 5,
            name: "assignRole",
            description: "Grant role access",
            permissionGroup: "Role Management",
            routes: [{ name: "/role/assign" }],
            status: "Active",
            createdAt: "2024-03-07T16:20:00Z",
        },
        {
            id: 6,
            name: "createRole",
            description: "Define new roles",
            permissionGroup: "Role Management",
            routes: [{ name: "/role/create" }],
            status: "Active",
            createdAt: "2024-03-06T09:50:00Z",
        },
        {
            id: 7,
            name: "editRole",
            description: "Modify role settings",
            permissionGroup: "Role Management",
            routes: [{ name: "/role/edit" }],
            status: "Active",
            createdAt: "2024-03-05T12:40:00Z",
        },
        {
            id: 8,
            name: "deleteRole",
            description: "Remove role",
            permissionGroup: "Role Management",
            routes: [{ name: "/role/delete" }],
            status: "Inactive",
            createdAt: "2024-03-04T15:00:00Z",
        },
        {
            id: 9,
            name: "managePermissions",
            description: "Set role permissions",
            permissionGroup: "Permission Management",
            routes: [{ name: "/permission/manage" }],
            status: "Active",
            createdAt: "2024-03-03T18:10:00Z",
        },
        {
            id: 10,
            name: "viewAuditLogs",
            description: "Check system logs",
            permissionGroup: "Admin Tools",
            routes: [{ name: "/logs/view" }],
            status: "Active",
            createdAt: "2024-03-02T20:05:00Z",
        },
    ],
};

export default samplePermissionTableData;
