const comprehensiveExamPatternData = {
    totalPages: 2,
    totalDocuments: 15,
    records: [
        {
            id: "1",
            name: "Full-Stack Web Development Certification",
            description: "Comprehensive assessment covering HTML, CSS, JavaScript, React, Node.js, and database management. Test your complete web development skills.",
            shuffleQuestions: true,
            shuffleSections: false,
            globalMarkingPolicy: {
                defaultCorrectMark: 2,
                defaultNegativeMark: 0.5,
            },
            sections: [{}, {}, {}, {}], // 4 sections
            securitySettings: {
                enableBrowserLockdown: true,
                disableRightClick: true,
                disableCopyPaste: true,
                preventTabSwitching: true,
                enableAIProctoring: true,
                allowedBrowsers: ["chrome", "firefox"],
                maxTabSwitches: 2,
                suspiciousActivityThreshold: 3,
                enableFullScreenMode: true,
                disableVirtualKeyboard: false,
            },
            accessControlSettings: {
                maxAttempts: 2,
                enableAccessCode: true,
                accessCode: "WEBDEV2024",
                allowedUserGroups: ["premium-students", "certified-learners"],
            },
            attemptRules: {
                maxSectionsToAttempt: 4,
                minSectionsToAttempt: 3,
                allowSectionNavigation: true,
                allowQuestionNavigation: true,
                allowBackNavigation: false,
            },
            resultsSettings: {
                showResultsImmediately: false,
                showCorrectAnswers: true,
                showDetailedAnalysis: true,
                enableResultsDownload: true,
                showRanking: true,
                showPerformanceAnalytics: true,
                enableCertificateGeneration: true,
                passingPercentage: 75,
                enableResultsEmail: true,
                resultVisibilityDelay: 24,
            },
            notificationSettings: {
                enableEmailNotifications: true,
                enableSMSNotifications: true,
                enablePushNotifications: true,
                sendExamReminders: true,
                reminderIntervals: [48, 24, 2],
                sendResultNotifications: true,
                sendStartNotifications: true,
                sendSubmissionConfirmation: true,
                notifyInstructors: true,
                notifyAdmins: true,
            },
            uiConfig: {
                theme: "professional",
                fontSize: "large",
                showTimer: true,
                languageSelector: true,
                accessibleMode: false,
            },
            status: "ACTIVE",
        },
        {
            id: "2",
            name: "JavaScript Fundamentals Quiz",
            description: "Quick assessment of JavaScript basics including variables, functions, arrays, and DOM manipulation.",
            shuffleQuestions: true,
            shuffleSections: true,
            globalMarkingPolicy: {
                defaultCorrectMark: 1,
                defaultNegativeMark: 0.25,
            },
            sections: [{}, {}], // 2 sections
            securitySettings: {
                enableBrowserLockdown: false,
                disableRightClick: false,
                disableCopyPaste: false,
                preventTabSwitching: false,
                enableAIProctoring: false,
                allowedBrowsers: ["chrome", "firefox", "safari"],
                maxTabSwitches: 5,
                suspiciousActivityThreshold: 8,
                enableFullScreenMode: false,
                disableVirtualKeyboard: false,
            },
            accessControlSettings: {
                maxAttempts: 3,
                enableAccessCode: false,
                accessCode: "",
                allowedUserGroups: [],
            },
            attemptRules: {
                maxSectionsToAttempt: 2,
                minSectionsToAttempt: 1,
                allowSectionNavigation: true,
                allowQuestionNavigation: true,
                allowBackNavigation: true,
            },
            resultsSettings: {
                showResultsImmediately: true,
                showCorrectAnswers: true,
                showDetailedAnalysis: false,
                enableResultsDownload: false,
                showRanking: false,
                showPerformanceAnalytics: true,
                enableCertificateGeneration: false,
                passingPercentage: 60,
                enableResultsEmail: false,
                resultVisibilityDelay: 0,
            },
            notificationSettings: {
                enableEmailNotifications: false,
                enableSMSNotifications: false,
                enablePushNotifications: true,
                sendExamReminders: false,
                reminderIntervals: [],
                sendResultNotifications: false,
                sendStartNotifications: false,
                sendSubmissionConfirmation: true,
                notifyInstructors: false,
                notifyAdmins: false,
            },
            uiConfig: {
                theme: "default",
                fontSize: "medium",
                showTimer: true,
                languageSelector: false,
                accessibleMode: false,
            },
            status: "ACTIVE",
        },
        {
            id: "3",
            name: "React Component Architecture",
            description: "Advanced React assessment focusing on component design patterns, hooks, context API, and performance optimization.",
            shuffleQuestions: false,
            shuffleSections: false,
            globalMarkingPolicy: {
                defaultCorrectMark: 3,
                defaultNegativeMark: 1,
            },
            sections: [{}, {}, {}], // 3 sections
            securitySettings: {
                enableBrowserLockdown: true,
                disableRightClick: true,
                disableCopyPaste: true,
                preventTabSwitching: true,
                enableAIProctoring: false,
                allowedBrowsers: ["chrome"],
                maxTabSwitches: 1,
                suspiciousActivityThreshold: 2,
                enableFullScreenMode: true,
                disableVirtualKeyboard: true,
            },
            accessControlSettings: {
                maxAttempts: 1,
                enableAccessCode: true,
                accessCode: "REACT2024",
                allowedUserGroups: ["advanced-developers"],
            },
            attemptRules: {
                maxSectionsToAttempt: 3,
                minSectionsToAttempt: 3,
                allowSectionNavigation: false,
                allowQuestionNavigation: true,
                allowBackNavigation: false,
            },
            resultsSettings: {
                showResultsImmediately: false,
                showCorrectAnswers: false,
                showDetailedAnalysis: true,
                enableResultsDownload: true,
                showRanking: true,
                showPerformanceAnalytics: true,
                enableCertificateGeneration: true,
                passingPercentage: 80,
                enableResultsEmail: true,
                resultVisibilityDelay: 48,
            },
            notificationSettings: {
                enableEmailNotifications: true,
                enableSMSNotifications: false,
                enablePushNotifications: true,
                sendExamReminders: true,
                reminderIntervals: [72, 24],
                sendResultNotifications: true,
                sendStartNotifications: true,
                sendSubmissionConfirmation: true,
                notifyInstructors: true,
                notifyAdmins: true,
            },
            uiConfig: {
                theme: "dark",
                fontSize: "medium",
                showTimer: true,
                languageSelector: false,
                accessibleMode: false,
            },
            status: "DRAFT",
        },
        {
            id: "4",
            name: "Database Design & SQL Mastery",
            description: "Comprehensive database assessment covering normalization, complex queries, indexing, and performance optimization.",
            shuffleQuestions: true,
            shuffleSections: true,
            globalMarkingPolicy: {
                defaultCorrectMark: 2,
                defaultNegativeMark: 0.5,
            },
            sections: [{}, {}, {}, {}, {}], // 5 sections
            securitySettings: {
                enableBrowserLockdown: true,
                disableRightClick: true,
                disableCopyPaste: false,
                preventTabSwitching: true,
                enableAIProctoring: true,
                allowedBrowsers: ["chrome", "firefox"],
                maxTabSwitches: 3,
                suspiciousActivityThreshold: 4,
                enableFullScreenMode: true,
                disableVirtualKeyboard: false,
            },
            accessControlSettings: {
                maxAttempts: 2,
                enableAccessCode: false,
                accessCode: "",
                allowedUserGroups: ["database-students"],
            },
            attemptRules: {
                maxSectionsToAttempt: 5,
                minSectionsToAttempt: 4,
                allowSectionNavigation: true,
                allowQuestionNavigation: true,
                allowBackNavigation: true,
            },
            resultsSettings: {
                showResultsImmediately: true,
                showCorrectAnswers: true,
                showDetailedAnalysis: true,
                enableResultsDownload: true,
                showRanking: false,
                showPerformanceAnalytics: true,
                enableCertificateGeneration: false,
                passingPercentage: 70,
                enableResultsEmail: true,
                resultVisibilityDelay: 0,
            },
            notificationSettings: {
                enableEmailNotifications: true,
                enableSMSNotifications: false,
                enablePushNotifications: true,
                sendExamReminders: true,
                reminderIntervals: [24, 1],
                sendResultNotifications: true,
                sendStartNotifications: true,
                sendSubmissionConfirmation: true,
                notifyInstructors: false,
                notifyAdmins: false,
            },
            uiConfig: {
                theme: "default",
                fontSize: "large",
                showTimer: true,
                languageSelector: true,
                accessibleMode: true,
            },
            status: "ACTIVE",
        },
        {
            id: "5",
            name: "Mobile App Development",
            description: "Cross-platform mobile development test covering React Native, Flutter, and native app deployment strategies.",
            shuffleQuestions: false,
            shuffleSections: true,
            globalMarkingPolicy: {
                defaultCorrectMark: 2.5,
                defaultNegativeMark: 0.75,
            },
            sections: [{}], // 1 section
            securitySettings: {
                enableBrowserLockdown: false,
                disableRightClick: false,
                disableCopyPaste: false,
                preventTabSwitching: false,
                enableAIProctoring: false,
                allowedBrowsers: ["chrome", "firefox", "safari", "edge"],
                maxTabSwitches: 10,
                suspiciousActivityThreshold: 15,
                enableFullScreenMode: false,
                disableVirtualKeyboard: false,
            },
            accessControlSettings: {
                maxAttempts: 5,
                enableAccessCode: false,
                accessCode: "",
                allowedUserGroups: [],
            },
            attemptRules: {
                maxSectionsToAttempt: 1,
                minSectionsToAttempt: 1,
                allowSectionNavigation: true,
                allowQuestionNavigation: true,
                allowBackNavigation: true,
            },
            resultsSettings: {
                showResultsImmediately: true,
                showCorrectAnswers: false,
                showDetailedAnalysis: false,
                enableResultsDownload: false,
                showRanking: false,
                showPerformanceAnalytics: false,
                enableCertificateGeneration: false,
                passingPercentage: 50,
                enableResultsEmail: false,
                resultVisibilityDelay: 0,
            },
            notificationSettings: {
                enableEmailNotifications: false,
                enableSMSNotifications: false,
                enablePushNotifications: false,
                sendExamReminders: false,
                reminderIntervals: [],
                sendResultNotifications: false,
                sendStartNotifications: false,
                sendSubmissionConfirmation: false,
                notifyInstructors: false,
                notifyAdmins: false,
            },
            uiConfig: {
                theme: "mobile",
                fontSize: "small",
                showTimer: false,
                languageSelector: false,
                accessibleMode: false,
            },
            status: "INACTIVE",
        },
        {
            id: "6",
            name: "Cloud Computing & DevOps",
            description: "Advanced assessment on AWS, Docker, Kubernetes, CI/CD pipelines, and infrastructure as code.",
            shuffleQuestions: true,
            shuffleSections: false,
            globalMarkingPolicy: {
                defaultCorrectMark: 4,
                defaultNegativeMark: 1.5,
            },
            sections: [{}, {}, {}, {}, {}, {}], // 6 sections
            securitySettings: {
                enableBrowserLockdown: true,
                disableRightClick: true,
                disableCopyPaste: true,
                preventTabSwitching: true,
                enableAIProctoring: true,
                allowedBrowsers: ["chrome"],
                maxTabSwitches: 0,
                suspiciousActivityThreshold: 1,
                enableFullScreenMode: true,
                disableVirtualKeyboard: true,
            },
            accessControlSettings: {
                maxAttempts: 1,
                enableAccessCode: true,
                accessCode: "DEVOPS2024",
                allowedUserGroups: ["enterprise-users", "devops-engineers"],
            },
            attemptRules: {
                maxSectionsToAttempt: 6,
                minSectionsToAttempt: 5,
                allowSectionNavigation: false,
                allowQuestionNavigation: false,
                allowBackNavigation: false,
            },
            resultsSettings: {
                showResultsImmediately: false,
                showCorrectAnswers: false,
                showDetailedAnalysis: true,
                enableResultsDownload: true,
                showRanking: true,
                showPerformanceAnalytics: true,
                enableCertificateGeneration: true,
                passingPercentage: 85,
                enableResultsEmail: true,
                resultVisibilityDelay: 72,
            },
            notificationSettings: {
                enableEmailNotifications: true,
                enableSMSNotifications: true,
                enablePushNotifications: true,
                sendExamReminders: true,
                reminderIntervals: [168, 72, 24, 2],
                sendResultNotifications: true,
                sendStartNotifications: true,
                sendSubmissionConfirmation: true,
                notifyInstructors: true,
                notifyAdmins: true,
            },
            uiConfig: {
                theme: "enterprise",
                fontSize: "medium",
                showTimer: true,
                languageSelector: false,
                accessibleMode: false,
            },
            status: "ACTIVE",
        },
        {
            id: "7",
            name: "Python Programming Basics",
            description: "Beginner-friendly Python assessment covering syntax, data structures, functions, and basic object-oriented programming.",
            shuffleQuestions: true,
            shuffleSections: false,
            globalMarkingPolicy: {
                defaultCorrectMark: 1,
                defaultNegativeMark: 0,
            },
            sections: [{}, {}], // 2 sections
            securitySettings: {
                enableBrowserLockdown: false,
                disableRightClick: false,
                disableCopyPaste: false,
                preventTabSwitching: false,
                enableAIProctoring: false,
                allowedBrowsers: ["chrome", "firefox", "safari", "edge"],
                maxTabSwitches: 999,
                suspiciousActivityThreshold: 999,
                enableFullScreenMode: false,
                disableVirtualKeyboard: false,
            },
            accessControlSettings: {
                maxAttempts: 999,
                enableAccessCode: false,
                accessCode: "",
                allowedUserGroups: [],
            },
            attemptRules: {
                maxSectionsToAttempt: 2,
                minSectionsToAttempt: 1,
                allowSectionNavigation: true,
                allowQuestionNavigation: true,
                allowBackNavigation: true,
            },
            resultsSettings: {
                showResultsImmediately: true,
                showCorrectAnswers: true,
                showDetailedAnalysis: true,
                enableResultsDownload: true,
                showRanking: false,
                showPerformanceAnalytics: true,
                enableCertificateGeneration: false,
                passingPercentage: 40,
                enableResultsEmail: false,
                resultVisibilityDelay: 0,
            },
            notificationSettings: {
                enableEmailNotifications: false,
                enableSMSNotifications: false,
                enablePushNotifications: true,
                sendExamReminders: false,
                reminderIntervals: [],
                sendResultNotifications: false,
                sendStartNotifications: false,
                sendSubmissionConfirmation: true,
                notifyInstructors: false,
                notifyAdmins: false,
            },
            uiConfig: {
                theme: "beginner",
                fontSize: "large",
                showTimer: false,
                languageSelector: true,
                accessibleMode: true,
            },
            status: "ACTIVE",
        },
        {
            id: "8",
            name: "Cybersecurity Fundamentals",
            description: "Essential cybersecurity concepts including encryption, network security, threat analysis, and incident response protocols.",
            shuffleQuestions: true,
            shuffleSections: true,
            globalMarkingPolicy: {
                defaultCorrectMark: 3,
                defaultNegativeMark: 1,
            },
            sections: [{}, {}, {}, {}], // 4 sections
            securitySettings: {
                enableBrowserLockdown: true,
                disableRightClick: true,
                disableCopyPaste: true,
                preventTabSwitching: true,
                enableAIProctoring: true,
                allowedBrowsers: ["chrome", "firefox"],
                maxTabSwitches: 1,
                suspiciousActivityThreshold: 2,
                enableFullScreenMode: true,
                disableVirtualKeyboard: false,
            },
            accessControlSettings: {
                maxAttempts: 2,
                enableAccessCode: true,
                accessCode: "SECURITY2024",
                allowedUserGroups: ["security-professionals"],
            },
            attemptRules: {
                maxSectionsToAttempt: 4,
                minSectionsToAttempt: 3,
                allowSectionNavigation: true,
                allowQuestionNavigation: true,
                allowBackNavigation: false,
            },
            resultsSettings: {
                showResultsImmediately: false,
                showCorrectAnswers: false,
                showDetailedAnalysis: true,
                enableResultsDownload: true,
                showRanking: false,
                showPerformanceAnalytics: true,
                enableCertificateGeneration: true,
                passingPercentage: 75,
                enableResultsEmail: true,
                resultVisibilityDelay: 24,
            },
            notificationSettings: {
                enableEmailNotifications: true,
                enableSMSNotifications: false,
                enablePushNotifications: true,
                sendExamReminders: true,
                reminderIntervals: [48, 12],
                sendResultNotifications: true,
                sendStartNotifications: true,
                sendSubmissionConfirmation: true,
                notifyInstructors: true,
                notifyAdmins: true,
            },
            uiConfig: {
                theme: "security",
                fontSize: "medium",
                showTimer: true,
                languageSelector: false,
                accessibleMode: false,
            },
            status: "DRAFT",
        },
        {
            id: "9",
            name: "JEE Main Mock Test 2024",
            examCode: "JEE-MOCK-2024-01",
            description: "Comprehensive JEE Main mock test covering Physics, Chemistry, and Mathematics with latest pattern and difficulty level.",
            startDate: "2024-03-15",
            startTime: "09:00",
            endTime: "12:00",
            examType: "mock",
            durationInMinutes: 180,
            isPublished: true,
            version: "1.0.0",
            languageOptions: ["english", "hindi"],
            tags: ["jee", "mock-test", "engineering", "competitive"],
            status: "PUBLISHED",
            createdAt: "2024-01-15T10:30:00Z",
            updatedAt: "2024-01-20T14:45:00Z",
        },
        {
            id: "10",
            name: "NEET Practice Test - Biology",
            examCode: "NEET-BIO-2024-01",
            description: "Focused biology practice test for NEET preparation with detailed explanations and performance analysis.",
            startDate: "2024-03-20",
            startTime: "14:00",
            endTime: "17:00",
            examType: "practice",
            durationInMinutes: 180,
            isPublished: false,
            version: "1.0.0",
            languageOptions: ["english"],
            tags: ["neet", "biology", "medical", "practice"],
            status: "DRAFT",
            createdAt: "2024-01-16T11:30:00Z",
            updatedAt: "2024-01-21T15:45:00Z",
        },
        {
            id: "11",
            name: "CAT Quantitative Aptitude Quiz",
            examCode: "CAT-QA-2024-01",
            description: "Quick assessment of quantitative aptitude skills for CAT preparation with time-bound questions.",
            startDate: "2024-03-25",
            startTime: "10:00",
            endTime: "11:30",
            examType: "quiz",
            durationInMinutes: 90,
            isPublished: true,
            version: "1.1.0",
            languageOptions: ["english"],
            tags: ["cat", "quantitative", "aptitude", "mba"],
            status: "SCHEDULED",
            createdAt: "2024-01-17T12:30:00Z",
            updatedAt: "2024-01-22T16:45:00Z",
        },
        {
            id: "12",
            name: "GATE Computer Science Mock",
            examCode: "GATE-CS-2024-01",
            description: "Full-length GATE Computer Science mock test with previous year question patterns and difficulty levels.",
            startDate: "2024-04-01",
            startTime: "09:30",
            endTime: "12:30",
            examType: "mock",
            durationInMinutes: 180,
            isPublished: false,
            version: "1.0.0",
            languageOptions: ["english"],
            tags: ["gate", "computer-science", "engineering", "postgraduate"],
            status: "DRAFT",
            createdAt: "2024-01-18T13:30:00Z",
            updatedAt: "2024-01-23T17:45:00Z",
        },
        {
            id: "13",
            name: "SSC CGL Tier 1 Assessment",
            examCode: "SSC-CGL-T1-2024-01",
            description: "Staff Selection Commission Combined Graduate Level Tier 1 examination with all four sections.",
            startDate: "2024-04-05",
            startTime: "11:00",
            endTime: "12:00",
            examType: "assessment",
            durationInMinutes: 60,
            isPublished: true,
            version: "1.0.0",
            languageOptions: ["english", "hindi"],
            tags: ["ssc", "cgl", "government", "competitive"],
            status: "PUBLISHED",
            createdAt: "2024-01-19T14:30:00Z",
            updatedAt: "2024-01-24T18:45:00Z",
        },
        {
            id: "14",
            name: "Banking PO Reasoning Test",
            examCode: "BANK-PO-REASON-2024-01",
            description: "Comprehensive reasoning ability test for banking PO examinations with logical and analytical questions.",
            startDate: "2024-04-10",
            startTime: "15:00",
            endTime: "16:30",
            examType: "practice",
            durationInMinutes: 90,
            isPublished: false,
            version: "1.0.0",
            languageOptions: ["english", "hindi"],
            tags: ["banking", "po", "reasoning", "finance"],
            status: "DRAFT",
            createdAt: "2024-01-20T15:30:00Z",
            updatedAt: "2024-01-25T19:45:00Z",
        },
        {
            id: "15",
            name: "UPSC Prelims General Studies",
            examCode: "UPSC-GS-2024-01",
            description: "UPSC Civil Services Preliminary examination General Studies paper with current affairs and static GK.",
            startDate: "2024-04-15",
            startTime: "09:00",
            endTime: "11:00",
            examType: "final",
            durationInMinutes: 120,
            isPublished: true,
            version: "1.0.0",
            languageOptions: ["english", "hindi"],
            tags: ["upsc", "prelims", "general-studies", "civil-services"],
            status: "SCHEDULED",
            createdAt: "2024-01-21T16:30:00Z",
            updatedAt: "2024-01-26T20:45:00Z",
        },
        {
            id: "16",
            name: "Class 12 Mathematics Final",
            examCode: "CLASS12-MATH-2024-01",
            description: "Comprehensive Class 12 Mathematics final examination covering all chapters with board exam pattern.",
            startDate: "2024-04-20",
            startTime: "10:30",
            endTime: "13:30",
            examType: "final",
            durationInMinutes: 180,
            isPublished: false,
            version: "1.0.0",
            languageOptions: ["english"],
            tags: ["class12", "mathematics", "board-exam", "final"],
            status: "DRAFT",
            createdAt: "2024-01-22T17:30:00Z",
            updatedAt: "2024-01-27T21:45:00Z",
        },
    ],
};

export default comprehensiveExamPatternData;
