const sampleCourseDetails = {
    id: "b3f0c3d2-5e67-4c5a-8b34-1a9f3c9a3f23",
    name: "John Doe",
    userId: "user_12345",
    bio: "Experienced software engineer with expertise in web development.",
    gender: "MALE",
    expertise: ["JavaScript", "React", "Node.js"],
    designation: "Senior Developer",
    qualification: "B.Tech in Computer Science",
    experience: 7,
    profileImageUrl: "https://demos.pixinvent.com/vuexy-vuejs-laravel-admin-template/demo-1/build/assets/avatar-1-DMk2FF1-.png",
    rating: 4.8,
    isActive: true,
    instituteId: "inst_789",
    languageCode: "en",
    socialLinks: {
        linkedin: "https://linkedin.com/in/johndoe",
        github: "https://github.com/johndoe",
    },
    achievements: ["Published research paper on AI", "Top performer award"],
    contactEmail: "johndoe@example.com",
    mobile: "+1234567890",
    createdAt: "2024-02-05T12:00:00Z",
    updatedAt: "2024-02-05T12:00:00Z",
    deletedAt: null,
};
export default sampleCourseDetails;
