const sampleUsersTableData = {
  totalPages: 5,
  totalDocuments: 1247,
  records: [
    {
      id: "1",
      name: "John Doe",
      email: "john.doe@example.com",
      mobile: "+1234567890",
      gender: "MALE",
      status: "ACTIVE",
      // profilePic: "/placeholder.svg?height=40&width=40",
      roles: ["Administrator", "Manager"],
      lastLogin: "2024-01-15T10:30:00Z",
      createdAt: "2024-01-01T00:00:00Z",
      department: "IT Department",
      jobTitle: "Senior Developer",
    },
    {
      id: "2",
      name: "Jane Smith",
      email: "jane.smith@example.com",
      mobile: "+1234567891",
      gender: "FEMALE",
      status: "ACTIVE",
      // profilePic: "/placeholder.svg?height=40&width=40",
      roles: ["Manager", "Instructor"],
      lastLogin: "2024-01-14T15:45:00Z",
      createdAt: "2024-01-02T00:00:00Z",
      department: "Education Department",
      jobTitle: "Content Manager",
    },
    {
      id: "3",
      name: "Mike Johnson",
      email: "mike.johnson@example.com",
      mobile: null,
      gender: "MALE",
      status: "INACTIVE",
      profilePic: null,
      roles: ["Student"],
      lastLogin: "2024-01-10T09:15:00Z",
      createdAt: "2024-01-03T00:00:00Z",
      department: null,
      jobTitle: null,
    },
    {
      id: "4",
      name: "Sarah Wilson",
      email: "sarah.wilson@example.com",
      mobile: "+1234567892",
      gender: "FEMALE",
      status: "SUSPENDED",
      // profilePic: "/placeholder.svg?height=40&width=40",
      roles: ["Student"],
      lastLogin: "2024-01-05T14:20:00Z",
      createdAt: "2024-01-04T00:00:00Z",
      department: null,
      jobTitle: null,
    },
    {
      id: "5",
      name: "Alex Chen",
      email: "alex.chen@example.com",
      mobile: "+1234567893",
      gender: "PREFER_NOT_TO_SAY",
      status: "PENDING",
      profilePic: null,
      roles: ["Student"],
      lastLogin: null,
      createdAt: "2024-01-14T00:00:00Z",
      department: null,
      jobTitle: null,
    },
    {
      id: "6",
      name: "Emily Davis",
      email: "emily.davis@example.com",
      mobile: "+1234567894",
      gender: "FEMALE",
      status: "ACTIVE",
      // profilePic: "/placeholder.svg?height=40&width=40",
      roles: ["Instructor", "Content Creator"],
      lastLogin: "2024-01-15T08:45:00Z",
      createdAt: "2024-01-05T00:00:00Z",
      department: "Education Department",
      jobTitle: "Senior Instructor",
    },
    {
      id: "7",
      name: "David Brown",
      email: "david.brown@example.com",
      mobile: "+1234567895",
      gender: "MALE",
      status: "ACTIVE",
      // profilePic: "/placeholder.svg?height=40&width=40",
      roles: ["Manager"],
      lastLogin: "2024-01-13T16:30:00Z",
      createdAt: "2024-01-06T00:00:00Z",
      department: "Operations",
      jobTitle: "Operations Manager",
    },
    {
      id: "8",
      name: "Lisa Anderson",
      email: "lisa.anderson@example.com",
      mobile: "+1234567896",
      gender: "FEMALE",
      status: "ACTIVE",
      profilePic: null,
      roles: ["Content Creator"],
      lastLogin: "2024-01-12T11:20:00Z",
      createdAt: "2024-01-07T00:00:00Z",
      department: "Content Team",
      jobTitle: "Content Specialist",
    },
  ],
}

export default sampleUsersTableData
