const sampleCoursesTableData = {
    totalPages: 10,
    totalDocuments: 100,
    records: [
        {
            id: "1",
            name: "Dr. Sarah Johnson",
            email: "sarah.johnson@example.com",
            phone: "+1 (555) 123-4567",
            title: "Senior Data Science Instructor",
            bio: "Dr. Johnson has over 15 years of experience in data science and machine learning. She previously worked at Google and has a PhD in Computer Science from Stanford.",
            expertise: ["Data Science", "Machine Learning", "Python", "Statistics", "Deep Learning"],
            rating: 4.9,
            courses: 12,
            students: 2450,
            imageUrl: "https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=150",
            availability: "Full-time",
            joinedDate: "2021-03-15",
        },
        {
            id: "2",
            name: "Prof. Michael Lee",
            email: "michael.lee@example.com",
            phone: "+1 (555) 234-5678",
            title: "AI & Robotics Instructor",
            bio: "Professor Lee has led several national projects in robotics and artificial intelligence.",
            expertise: ["Artificial Intelligence", "Robotics", "C++", "Control Systems"],
            rating: 4.8,
            courses: 8,
            students: 1980,
            imageUrl: "https://images.pexels.com/photos/2182970/pexels-photo-2182970.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=150",
            availability: "Part-time",
            joinedDate: "2020-11-22",
        },
        {
            id: "3",
            name: "Dr. Emily Chen",
            email: "emily.chen@example.com",
            phone: "+1 (555) 345-6789",
            title: "Cybersecurity Expert",
            bio: "Emily specializes in ethical hacking and risk management.",
            expertise: ["Cybersecurity", "Ethical Hacking", "Linux", "Networking"],
            rating: 4.7,
            courses: 10,
            students: 2730,
            imageUrl: "https://images.pexels.com/photos/1130626/pexels-photo-1130626.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=150",
            availability: "Full-time",
            joinedDate: "2019-08-12",
        },
        {
            id: "4",
            name: "Mr. David Kim",
            email: "david.kim@example.com",
            phone: "+1 (555) 456-7890",
            title: "Cloud Computing Instructor",
            bio: "David is a certified AWS and Azure trainer. His cloud infrastructure courses are highly rated.",
            expertise: ["AWS", "Azure", "Cloud Architecture", "DevOps"],
            rating: 4.6,
            courses: 9,
            students: 2230,
            imageUrl: "https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=150",
            availability: "Contract",
            joinedDate: "2022-01-10",
        },
        {
            id: "5",
            name: "Ms. Aisha Patel",
            email: "aisha.patel@example.com",
            phone: "+1 (555) 567-8901",
            title: "Frontend Development Instructor",
            bio: "Aisha is a frontend wizard and ReactJS evangelist.",
            expertise: ["ReactJS", "JavaScript", "CSS", "UI/UX"],
            rating: 4.95,
            courses: 7,
            students: 2100,
            imageUrl: "https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=150",
            availability: "Full-time",
            joinedDate: "2023-04-01",
        },
        {
            id: "6",
            name: "Mr. James Brown",
            email: "james.brown@example.com",
            phone: "+1 (555) 678-9012",
            title: "Backend Engineering Mentor",
            bio: "James is known for simplifying backend systems and architecture design.",
            expertise: ["Node.js", "Express", "MongoDB", "Docker", "Microservices"],
            rating: 4.8,
            courses: 6,
            students: 1800,
            imageUrl: "https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=150",
            availability: "Part-time",
            joinedDate: "2021-07-15",
        },
        {
            id: "7",
            name: "Dr. Sofia Martinez",
            email: "sofia.martinez@example.com",
            phone: "+1 (555) 789-0123",
            title: "Data Analytics Instructor",
            bio: "Dr. Martinez has worked on data insights with Fortune 100 clients.",
            expertise: ["SQL", "Power BI", "Excel", "Data Visualization"],
            rating: 4.85,
            courses: 5,
            students: 1600,
            imageUrl: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=150",
            availability: "Full-time",
            joinedDate: "2020-03-20",
        },
        {
            id: "8",
            name: "Mr. Kevin Zhang",
            email: "kevin.zhang@example.com",
            phone: "+1 (555) 890-1234",
            title: "Mobile App Development Instructor",
            bio: "Kevin has launched multiple top-rated apps on both iOS and Android.",
            expertise: ["Flutter", "React Native", "Swift", "Kotlin"],
            rating: 4.75,
            courses: 4,
            students: 1400,
            imageUrl: "https://images.pexels.com/photos/1704488/pexels-photo-1704488.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=150",
            availability: "Freelance",
            joinedDate: "2022-06-11",
        },
        {
            id: "9",
            name: "Ms. Rachel Green",
            email: "rachel.green@example.com",
            phone: "+1 (555) 901-2345",
            title: "Digital Marketing Instructor",
            bio: "Rachel teaches growth hacking and advanced digital marketing strategies.",
            expertise: ["SEO", "Google Ads", "Social Media", "Content Marketing"],
            rating: 4.6,
            courses: 6,
            students: 1550,
            imageUrl: "https://images.pexels.com/photos/415829/pexels-photo-415829.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=150",
            availability: "Part-time",
            joinedDate: "2023-02-05",
        },
        {
            id: "10",
            name: "Dr. Omar Hassan",
            email: "omar.hassan@example.com",
            phone: "+1 (555) 012-3456",
            title: "Blockchain & Web3 Instructor",
            bio: "Omar has extensive experience in decentralized systems and smart contracts.",
            expertise: ["Blockchain", "Ethereum", "Solidity", "Web3.js"],
            rating: 4.9,
            courses: 3,
            students: 1300,
            imageUrl: "https://images.pexels.com/photos/3184328/pexels-photo-3184328.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=150",
            availability: "Full-time",
            joinedDate: "2021-09-01",
        },
    ],
};

export default sampleCoursesTableData;
