const sampleRoutesTableData = {
  totalPages: 3,
  totalDocuments: 45,
  records: [
    {
      id: "1",
      name: "Get Users",
      basePath: "/api/v1",
      endPoint: "/users",
      method: "GET",
      description: "Retrieve all users from the system",
      isPublic: false,
      type: "API",
    },
    {
      id: "2",
      name: "Create User",
      basePath: "/api/v1",
      endPoint: "/users",
      method: "POST",
      description: "Create a new user account",
      isPublic: false,
      type: "API",
    },
    {
      id: "3",
      name: "Update User",
      basePath: "/api/v1",
      endPoint: "/users/:id",
      method: "PUT",
      description: "Update user information",
      isPublic: false,
      type: "API",
    },
    {
      id: "4",
      name: "Delete User",
      basePath: "/api/v1",
      endPoint: "/users/:id",
      method: "DELETE",
      description: "Delete a user account",
      isPublic: false,
      type: "API",
    },
    {
      id: "5",
      name: "Public Health Check",
      basePath: "/api",
      endPoint: "/health",
      method: "GET",
      description: "System health check endpoint",
      isPublic: true,
      type: "API",
    },
    {
      id: "6",
      name: "Get Courses",
      basePath: "/api/v1",
      endPoint: "/courses",
      method: "GET",
      description: "Retrieve all courses",
      isPublic: false,
      type: "API",
    },
    {
      id: "7",
      name: "Create Course",
      basePath: "/api/v1",
      endPoint: "/courses",
      method: "POST",
      description: "Create a new course",
      isPublic: false,
      type: "API",
    },
    {
      id: "8",
      name: "Login",
      basePath: "/auth",
      endPoint: "/login",
      method: "POST",
      description: "User authentication endpoint",
      isPublic: true,
      type: "WEB",
    },
  ],
}

export default sampleRoutesTableData
