/**
 * Sample question data for testing and development
 */
export const sampleQuestionData = {
  questionId: "q_001",
  type: "MCQ",
  text: "What is the capital of France?",
  image: "",
  options: [
    { id: "a", text: "London", isCorrect: false },
    { id: "b", text: "Berlin", isCorrect: false },
    { id: "c", text: "Paris", isCorrect: true },
    { id: "d", text: "Madrid", isCorrect: false },
  ],
  answer: { correctOption: "c" },
  tags: ["geography", "europe", "capitals"],
  difficulty: "easy",
  language: "en",
  points: 1,
  timeLimit: 60,
  explanation: "Paris is the capital and largest city of France.",
  category: "Geography",
  subject: "Social Studies",
  topic: "World Capitals",
  subtopic: "European Capitals",
  isPublic: false,
  allowPartialCredit: false,
  createdBy: "teacher@example.com",
  createdAt: "2024-01-15T10:30:00Z",
  updatedAt: "2024-01-20T14:45:00Z",
  status: "ACTIVE",
  version: "1.0.0",
  metadata: {
    bloomsTaxonomy: "Remember",
    cognitiveLevel: "Basic",
    estimatedTime: 45,
    source: "Original",
    references: [],
  },
  accessibility: {
    altText: "",
    audioDescription: "",
    largeText: false,
    highContrast: false,
  },
  analytics: {
    timesUsed: 0,
    averageScore: 0,
    averageTime: 0,
    difficultyRating: 0,
  },
}
