/**
 * Sample exam builder data for testing and development
 */
export const sampleExamBuilderData = {
  name: "JEE Main Mock Test 2024",
  examCode: "JEE-MOCK-2024-01",
  description:
    "Comprehensive JEE Main mock test covering Physics, Chemistry, and Mathematics with latest pattern and difficulty level.",
  startDate: "2024-03-15",
  startTime: "09:00",
  endTime: "12:00",
  examType: "mock",
  durationInMinutes: 180,
  isPublished: false,
  version: "1.0.0",
  languageOptions: ["english", "hindi"],
  tags: ["jee", "mock-test", "engineering", "competitive"],

  // Selected exam pattern (JSON field)
  examPattern: {
    name: "JEE Main Pattern",
    description: "Joint Entrance Examination Main pattern with Physics, Chemistry, and Mathematics",
    durationInMinutes: 180,
    shuffleQuestions: true,
    shuffleSections: false,
    globalMarkingPolicy: {
      defaultCorrectMark: 4,
      defaultNegativeMark: 1,
    },
    sections: [
      {
        sectionId: "PHYSICS",
        name: "Physics",
        isCompulsory: true,
        questionsCount: 30,
        questionsToAttempt: 25,
        shuffleQuestions: true,
        passingMarks: 40,
        questionGroups: [
          {
            range: [1, 20],
            marksPerQuestion: 4,
            negativeMarks: 1,
            questionType: "MCQ",
          },
          {
            range: [21, 30],
            marksPerQuestion: 4,
            negativeMarks: 0,
            questionType: "Numeric",
          },
        ],
        subjectTag: "physics",
        sectionTimeLimit: null,
      },
      {
        sectionId: "CHEMISTRY",
        name: "Chemistry",
        isCompulsory: true,
        questionsCount: 30,
        questionsToAttempt: 25,
        shuffleQuestions: true,
        passingMarks: 40,
        questionGroups: [
          {
            range: [31, 50],
            marksPerQuestion: 4,
            negativeMarks: 1,
            questionType: "MCQ",
          },
          {
            range: [51, 60],
            marksPerQuestion: 4,
            negativeMarks: 0,
            questionType: "Numeric",
          },
        ],
        subjectTag: "chemistry",
        sectionTimeLimit: null,
      },
      {
        sectionId: "MATHEMATICS",
        name: "Mathematics",
        isCompulsory: true,
        questionsCount: 30,
        questionsToAttempt: 25,
        shuffleQuestions: true,
        passingMarks: 40,
        questionGroups: [
          {
            range: [61, 80],
            marksPerQuestion: 4,
            negativeMarks: 1,
            questionType: "MCQ",
          },
          {
            range: [81, 90],
            marksPerQuestion: 4,
            negativeMarks: 0,
            questionType: "Numeric",
          },
        ],
        subjectTag: "mathematics",
        sectionTimeLimit: null,
      },
    ],
    attemptRules: {
      maxSectionsToAttempt: 3,
      minSectionsToAttempt: 3,
      allowSectionNavigation: true,
      allowQuestionNavigation: true,
      allowBackNavigation: true,
    },
    securitySettings: {
      enableBrowserLockdown: true,
      disableRightClick: true,
      disableCopyPaste: true,
      preventTabSwitching: true,
      enableAIProctoring: false,
      allowedBrowsers: ["chrome", "firefox"],
      maxTabSwitches: 2,
      suspiciousActivityThreshold: 3,
      enableFullScreenMode: true,
      disableVirtualKeyboard: false,
    },
    accessControlSettings: {
      maxAttempts: 1,
      enableAccessCode: false,
      accessCode: "",
      allowedUserGroups: [],
    },
    resultsSettings: {
      showResultsImmediately: false,
      showCorrectAnswers: true,
      showDetailedAnalysis: true,
      enableResultsDownload: true,
      showRanking: true,
      showPerformanceAnalytics: true,
      enableCertificateGeneration: false,
      passingPercentage: 40,
      enableResultsEmail: false,
      resultVisibilityDelay: 24,
    },
    notificationSettings: {
      enableEmailNotifications: true,
      enableSMSNotifications: false,
      enablePushNotifications: true,
      sendExamReminders: true,
      reminderIntervals: [24, 2],
      sendResultNotifications: true,
      sendStartNotifications: true,
      sendSubmissionConfirmation: true,
      notifyInstructors: false,
      notifyAdmins: false,
    },
    uiConfig: {
      theme: "default",
      fontSize: "medium",
      showTimer: true,
      languageSelector: true,
      accessibleMode: false,
    },
  },

  status: "DRAFT",
  createdAt: "2024-01-15T10:30:00Z",
  updatedAt: "2024-01-20T14:45:00Z",
  createdBy: "admin@example.com",
}
