export const sampleExamData = {
    examName: "RRB NTPC Stage 1",
    examCode: "RRB-NTPC-2025",
    durationInMinutes: 90,
    languageOptions: ["English", "Hindi"],
    shuffleQuestions: true,
    shuffleSections: false,
    globalMarkingPolicy: {
        defaultCorrectMark: 1,
        defaultNegativeMark: 0.33,
    },
    sections: [
        {
            sectionId: "S1",
            name: "Mathematics",
            isCompulsory: true,
            questionsCount: 30,
            questionsToAttempt: 30,
            shuffleQuestions: true,
            questionGroups: [
                {
                    range: [1, 15],
                    marksPerQuestion: 2,
                    negativeMarks: 1,
                    questionType: "MCQ",
                },
                {
                    range: [16, 30],
                    marksPerQuestion: 4,
                    negativeMarks: 0.5,
                    questionType: "MCQ",
                },
            ],
            subjectTag: "math",
            sectionTimeLimit: null,
        },
        {
            sectionId: "S2",
            name: "General Intelligence and Reasoning",
            isCompulsory: true,
            questionsCount: 30,
            questionsToAttempt: 30,
            shuffleQuestions: true,
            questionGroups: [
                {
                    range: [31, 60],
                    marksPerQuestion: 1,
                    negativeMarks: 0.33,
                    questionType: "MCQ",
                },
            ],
            subjectTag: "reasoning",
            sectionTimeLimit: null,
        },
        {
            sectionId: "S3",
            name: "General Awareness",
            isCompulsory: false,
            questionsCount: 20,
            questionsToAttempt: 15,
            shuffleQuestions: false,
            questionGroups: [
                {
                    range: [61, 80],
                    marksPerQuestion: 2,
                    negativeMarks: 0.5,
                    questionType: "MCQ",
                },
            ],
            subjectTag: "gk",
            sectionTimeLimit: 20,
        },
    ],
    attemptRules: {
        maxSectionsToAttempt: 3,
        minSectionsToAttempt: 2,
        allowSectionNavigation: true,
        allowQuestionNavigation: true,
        allowBackNavigation: true,
        autoSubmitOnTimeEnd: true,
        showUnattemptedCount: true,
    },
    submissionRules: {
        allowManualSubmit: true,
        autoSubmitOnTimeout: true,
        confirmBeforeSubmit: true,
    },
    uiConfig: {
        theme: "railway-theme",
        fontSize: "medium",
        showTimer: true,
        languageSelector: true,
        accessibleMode: false,
    },
    status: "PUBLISHED",
};
