const sampleInstructorTableData = {
    totalPages: 10,
    totalDocuments: 100,
    data: [
        {
            id: "b3f0c3d2-5e67-4c5a-8b34-1a9f3c9a3f23",
            name: "John Doe",
            userId: "user_12345",
            bio: "Experienced software engineer with expertise in web development.",
            gender: "MALE",
            expertise: ["JavaScript", "React", "Node.js"],
            designation: "Senior Developer",
            qualification: "B.Tech in Computer Science",
            experience: 7,
            profileImageUrl: "https://demos.pixinvent.com/vuexy-vuejs-laravel-admin-template/demo-1/build/assets/avatar-1-DMk2FF1-.png",
            rating: 4.8,
            isActive: true,
            instituteId: "inst_789",
            languageCode: "en",
            socialLinks: {
                linkedin: "https://linkedin.com/in/johndoe",
                github: "https://github.com/johndoe",
            },
            achievements: ["Published research paper on AI", "Top performer award"],
            contactEmail: "johndoe@example.com",
            mobile: "+1234567890",
            createdAt: "2024-02-05T12:00:00Z",
            updatedAt: "2024-02-05T12:00:00Z",
            deletedAt: null,
        },
        {
            id: "f0d1a2b3-4c5d-6e7f-8g90-1h2i3j4k5l6m",
            name: "Jane Smith",
            userId: "user_67890",
            bio: "Data scientist with a passion for AI and machine learning.",
            gender: "FEMALE",
            expertise: ["Python", "Machine Learning", "Data Science"],
            designation: "Lead Data Scientist",
            qualification: "M.Sc in Data Science",
            experience: 5,
            profileImageUrl: "https://demos.pixinvent.com/vuexy-vuejs-laravel-admin-template/demo-1/build/assets/avatar-2-D5OQ4OGs.png",
            rating: 4.9,
            isActive: true,
            instituteId: "inst_456",
            languageCode: "en",
            socialLinks: {
                linkedin: "https://linkedin.com/in/janesmith",
                kaggle: "https://kaggle.com/janesmith",
            },
            achievements: ["Developed AI-powered analytics tool", "Guest speaker at AI conferences"],
            contactEmail: "janesmith@example.com",
            mobile: "+9876543210",
            createdAt: "2024-02-01T15:30:00Z",
            updatedAt: "2024-02-03T10:20:00Z",
            deletedAt: null,
        },
        {
            id: "b3f0c3d2-5e67-4c5a-8b34-1a9f3c9a3f23",
            name: "John Doe",
            userId: "user_12345",
            bio: "Experienced software engineer with expertise in web development.",
            gender: "MALE",
            expertise: ["JavaScript", "React", "Node.js"],
            designation: "Senior Developer",
            qualification: "B.Tech in Computer Science",
            experience: 7,
            profileImageUrl: "https://demos.pixinvent.com/vuexy-vuejs-laravel-admin-template/demo-1/build/assets/avatar-1-DMk2FF1-.png",
            rating: 4.8,
            isActive: true,
            instituteId: "inst_789",
            languageCode: "en",
            socialLinks: {
                linkedin: "https://linkedin.com/in/johndoe",
                github: "https://github.com/johndoe",
            },
            achievements: ["Published research paper on AI", "Top performer award"],
            contactEmail: "johndoe@example.com",
            mobile: "+1234567890",
            createdAt: "2024-02-05T12:00:00Z",
            updatedAt: "2024-02-05T12:00:00Z",
            deletedAt: null,
        },
        {
            id: "f0d1a2b3-4c5d-6e7f-8g90-1h2i3j4k5l6m",
            name: "Jane Smith",
            userId: "user_67890",
            bio: "Data scientist with a passion for AI and machine learning.",
            gender: "FEMALE",
            expertise: ["Python", "Machine Learning", "Data Science"],
            designation: "Lead Data Scientist",
            qualification: "M.Sc in Data Science",
            experience: 5,
            profileImageUrl: "https://demos.pixinvent.com/vuexy-vuejs-laravel-admin-template/demo-1/build/assets/avatar-2-D5OQ4OGs.png",
            rating: 4.9,
            isActive: true,
            instituteId: "inst_456",
            languageCode: "en",
            socialLinks: {
                linkedin: "https://linkedin.com/in/janesmith",
                kaggle: "https://kaggle.com/janesmith",
            },
            achievements: ["Developed AI-powered analytics tool", "Guest speaker at AI conferences"],
            contactEmail: "janesmith@example.com",
            mobile: "+9876543210",
            createdAt: "2024-02-01T15:30:00Z",
            updatedAt: "2024-02-03T10:20:00Z",
            deletedAt: null,
        },
    ],
};

export default sampleInstructorTableData;
