import GlobalICONS from "@/lib/utils/icons";
import courseFormConstants from "../utils/constants";

const DEFAULT_GRID = 3;

const generalInformationSection = [
    {
        type: "rowHeader",
        label: "General Information",
        icon: GlobalICONS.INFORMATION,
        description: "Provide essential details about the course, such as name, category, and language.",
    },
    {
        type: "text",
        name: "name",
        label: "Course Name",
        grid: DEFAULT_GRID,
        placeholder: "Enter course name",
        validationRules: { required: true },
        validateOnChange: true,
    },
    {
        type: "text",
        name: "code",
        label: "Course Code",
        grid: DEFAULT_GRID,
        placeholder: "Enter unique course code",
        validationRules: { required: true },
        validateOnChange: true,
    },
    {
        type: "select",
        name: "categoryId",
        label: "Category",
        grid: DEFAULT_GRID,
        placeholder: "Select course category",
        options: courseFormConstants?.categories || [],
        validationRules: { required: true },
        validateOnChange: true,
    },
    {
        type: "select",
        name: "languageCode",
        label: "Language",
        grid: DEFAULT_GRID,
        placeholder: "Select course language",
        options: courseFormConstants.languages,
        validationRules: { required: true },
        validateOnChange: true,
    },
    {
        type: "select",
        name: "difficultyLevel",
        label: "Difficulty Level",
        grid: DEFAULT_GRID,
        placeholder: "Select difficulty level",
        options: courseFormConstants.difficultyLevels,
        validationRules: { required: true },
        validateOnChange: true,
    },
    {
        type: "select",
        name: "status",
        label: "Status",
        grid: DEFAULT_GRID,
        placeholder: "Select course status",
        options: courseFormConstants.courseStatusOptions,
        validationRules: { required: true },
        validateOnChange: true,
    },
    {
        type: "select",
        name: "instructorIds",
        label: "Instructors",
        grid: DEFAULT_GRID,
        multiple: true,
        placeholder: "Select instructors",
        options: courseFormConstants.instructors || [],
        validationRules: { required: true },
        validateOnChange: true,
    },
    {
        type: "select",
        name: "tags",
        label: "Tags",
        grid: DEFAULT_GRID,
        multiple: true,
        placeholder: "Select tags",
        options: courseFormConstants.tags || [],
        validationRules: { required: false },
        validateOnChange: true,
    },
    {
        type: "text",
        name: "durations",
        label: "Duration",
        grid: DEFAULT_GRID,
        placeholder: "Enter course duration",
        validationRules: { required: false },
        validateOnChange: true,
    },
    {
        type: "textarea",
        name: "description",
        label: "Description",
        grid: 2,
        placeholder: "Provide a detailed course description...",
        editorType: "rich",
        validationRules: { required: true },
        validateOnChange: true,
    },
    {
        type: "textarea",
        name: "summary",
        label: "Summary",
        grid: 2,
        placeholder: "Write a brief course summary...",
        validationRules: { required: true },
        validateOnChange: true,
    },
];

export default generalInformationSection;
