const sampleSubscriptionsTableData = {
  totalPages: 3,
  totalDocuments: 8,
  records: [
    {
      id: "1",
      planName: "Premium Monthly",
      planType: "monthly",
      description: "Get unlimited access to all courses with premium features and priority support.",
      price: 29.99,
      originalPrice: 39.99,
      currency: "USD",
      durationValue: 1,
      durationUnit: "months",
      isPopular: true,
      isTrial: false,
      hasCertificate: true,
      isActive: true,
      features: [
        "Unlimited Course Access",
        "Priority Support",
        "Certificate Included",
        "Mobile App Access",
        "Offline Content",
      ],
      enrollmentCount: 1250,
      maxEnrollments: 2000,
    },
    {
      id: "2",
      planName: "Basic Yearly",
      planType: "yearly",
      description: "Annual subscription with basic features and standard support.",
      price: 199.99,
      originalPrice: 299.99,
      currency: "USD",
      durationValue: 1,
      durationUnit: "years",
      isPopular: false,
      isTrial: false,
      hasCertificate: true,
      isActive: true,
      features: ["Course Access", "Standard Support", "Certificate Included", "Mobile App Access"],
      enrollmentCount: 850,
      maxEnrollments: 1500,
    },
    {
      id: "3",
      planName: "Free Trial",
      planType: "monthly",
      description: "Try our platform for free with limited access to courses.",
      price: 0,
      originalPrice: null,
      currency: "USD",
      durationValue: 7,
      durationUnit: "days",
      isPopular: false,
      isTrial: true,
      hasCertificate: false,
      isActive: true,
      features: ["Limited Course Access", "Basic Support", "7-Day Trial"],
      enrollmentCount: 2500,
      maxEnrollments: null,
    },
    {
      id: "4",
      planName: "Lifetime Access",
      planType: "lifetime",
      description: "One-time payment for lifetime access to all current and future courses.",
      price: 999.99,
      originalPrice: 1299.99,
      currency: "USD",
      durationValue: null,
      durationUnit: "lifetime",
      isPopular: false,
      isTrial: false,
      hasCertificate: true,
      isActive: true,
      features: [
        "Lifetime Course Access",
        "Premium Support",
        "Certificate Included",
        "All Future Courses",
        "Mobile App Access",
        "Offline Content",
        "Priority Updates",
      ],
      enrollmentCount: 320,
      maxEnrollments: 500,
    },
    {
      id: "5",
      planName: "Student Monthly",
      planType: "monthly",
      description: "Special discounted plan for students with verification required.",
      price: 14.99,
      originalPrice: 29.99,
      currency: "USD",
      durationValue: 1,
      durationUnit: "months",
      isPopular: false,
      isTrial: false,
      hasCertificate: true,
      isActive: true,
      features: ["Student Discount", "Course Access", "Standard Support", "Certificate Included"],
      enrollmentCount: 650,
      maxEnrollments: 1000,
    },
    {
      id: "6",
      planName: "Enterprise",
      planType: "yearly",
      description: "Custom enterprise solution with team management and advanced analytics.",
      price: 2999.99,
      originalPrice: null,
      currency: "USD",
      durationValue: 1,
      durationUnit: "years",
      isPopular: false,
      isTrial: false,
      hasCertificate: true,
      isActive: true,
      features: [
        "Unlimited Team Access",
        "Advanced Analytics",
        "Custom Branding",
        "Priority Support",
        "Team Management",
        "Bulk Certificates",
      ],
      enrollmentCount: 45,
      maxEnrollments: 100,
    },
    {
      id: "7",
      planName: "Pro Quarterly",
      planType: "quarterly",
      description: "Professional plan billed every 3 months with advanced features.",
      price: 79.99,
      originalPrice: 99.99,
      currency: "USD",
      durationValue: 3,
      durationUnit: "months",
      isPopular: false,
      isTrial: false,
      hasCertificate: true,
      isActive: false,
      features: ["Pro Features", "Priority Support", "Certificate Included", "Advanced Tools"],
      enrollmentCount: 180,
      maxEnrollments: 300,
    },
    {
      id: "8",
      planName: "Weekend Warrior",
      planType: "weekly",
      description: "Short-term access perfect for intensive weekend learning sessions.",
      price: 9.99,
      originalPrice: null,
      currency: "USD",
      durationValue: 1,
      durationUnit: "weeks",
      isPopular: false,
      isTrial: false,
      hasCertificate: false,
      isActive: true,
      features: ["1 Week Access", "Basic Support", "Mobile Access"],
      enrollmentCount: 420,
      maxEnrollments: null,
    },
  ],
}

export default sampleSubscriptionsTableData
