const sampleUsersTableData = {
    totalPages: 16,
    totalDocuments: 156,
    records: [
        {
            _id: "6486cae1284e17286e06f902c",
            name: "Beverlie Krabbe",
            email: "bkrabbe1d@home.pl",
            role: "Editor",
            plan: "Company",
            billing: "Manual-Case",
            status: "Active",
            image: "https://demos.pixinvent.com/vuexy-vuejs-laravel-admin-template/demo-1/build/assets/avatar-1-DMk2FF1-.png",
        },
        {
            _id: "6486cae1284e1728606f902ec",
            name: "Paulie Durber",
            email: "pdurber1c@gov.uk",
            role: "Subscriber",
            plan: "Team",
            billing: "Manual-PayPal",
            status: "Inactive",
            image: "https://demos.pixinvent.com/vuexy-vuejs-laravel-admin-template/demo-1/build/assets/avatar-2-D5OQ4OGs.png",
        },
        {
            _id: "e45436565",
            name: "Onfre Wind",
            email: "owind1b@yandex.ru",
            role: "Admin",
            plan: "Basic",
            billing: "Manual-PayPal",
            status: "Pending",
            image: "https://demos.pixinvent.com/vuexy-vuejs-laravel-admin-template/demo-1/build/assets/avatar-3-BxDW4ia1.png",
        },
        {
            Id: "e454365",
            name: "Karena Courtliff",
            email: "kcourtliff1a@bbc.co.uk",
            role: "Admin",
            plan: "Basic",
            billing: "Manual-Credit Card",
            status: "Active",
            image: "https://demos.pixinvent.com/vuexy-vuejs-laravel-admin-template/demo-1/build/assets/avatar-6-B6-OBpiL.png",
        },
        {
            Id: "e454365",
            name: "Saunder Offner",
            email: "soffner19@mac.com",
            role: "maintainer",
            plan: "enterprise",
            billing: "Manual-Credit Card",
            status: "Pending",
            image: "https://demos.pixinvent.com/vuexy-vuejs-laravel-admin-template/demo-1/build/assets/avatar-4-CtU30128.png",
        },
        {
            Id: "e454365",
            name: "Corrie Perot",
            email: "cperot18@goo.ne.jp",
            role: "subscriber",
            plan: "team",
            billing: "Manual-Credit Card",
            status: "Pending",
            image: "https://demos.pixinvent.com/vuexy-vuejs-laravel-admin-template/demo-1/build/assets/avatar-5-CmycerLe.png",
        },
        {
            Id: "e454365",
            name: "Vladamir Koschek",
            email: "vkoschek17@abc.net.au",
            role: "author",
            plan: "team",
            billing: "Manual-Credit Card",
            status: "Active",
            image: "https://demos.pixinvent.com/vuexy-vuejs-laravel-admin-template/demo-1/build/assets/avatar-1-DMk2FF1-.png",
        },
        {
            Id: "e454365",
            name: "Micaela McNirlan",
            email: "mmcnirlan16@hc360.com",
            role: "admin",
            plan: "basic",
            billing: "Auto Debit",
            status: "Inactive",
            image: "https://demos.pixinvent.com/vuexy-vuejs-laravel-admin-template/demo-1/build/assets/avatar-2-D5OQ4OGs.png",
        },
        {
            Id: "e454365",
            name: "Benedetto Rossiter",
            email: "brossiter15@craigslist.org",
            role: "editor",
            plan: "team",
            billing: "Auto Debit",
            status: "Inactive",
            // image: "https://demos.pixinvent.com/vuexy-vuejs-laravel-admin-template/demo-1/build/assets/avatar-1-DMk2FF1-.png",
        },
        {
            Id: "e454365",
            name: "Edwina Baldetti",
            email: "ebaldetti14@theguardian.com",
            role: "maintainer",
            plan: "team",
            billing: "Auto Debit",
            status: "Pending",
            image: "https://demos.pixinvent.com/vuexy-vuejs-laravel-admin-template/demo-1/build/assets/avatar-1-DMk2FF1-.png",
        },
    ],
};

export default sampleUsersTableData;
