export const mockUserDetails = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    mobile: "+1-555-0123",
    gender: "MALE",
    status: "ACTIVE",
    profilePic: "/placeholder.svg?height=80&width=80",
    roles: ["Administrator", "Content Manager"],
    createdAt: "2023-01-15T10:30:00Z",
    updatedAt: "2024-01-10T14:20:00Z",
    lastLogin: "2024-01-18T09:15:00Z",
    location: "New York, USA",
    timezone: "America/New_York",
    department: "IT Department",
    jobTitle: "Senior Developer",
    manager: "Jane Smith",
    employeeId: "EMP001",
    bio: "Experienced full-stack developer with expertise in React, Node.js, and cloud technologies. Passionate about creating scalable and user-friendly applications.",
    skills: ["JavaScript", "React", "Node.js", "Python", "AWS", "Docker"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/johndoe",
      github: "https://github.com/johndoe",
      twitter: "https://twitter.com/johndoe",
    },
    preferences: {
      theme: "system",
      language: "en",
      notifications: {
        email: true,
        push: false,
        sms: true,
      },
    },
    securitySettings: {
      twoFactorEnabled: true,
      lastPasswordChange: "2023-12-01T10:00:00Z",
      loginAttempts: 0,
      accountLocked: false,
    },
    activityLog: [
      {
        id: 1,
        action: "Login",
        timestamp: "2024-01-18T09:15:00Z",
        ipAddress: "192.168.1.100",
        userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        location: "New York, USA",
      },
      {
        id: 2,
        action: "Profile Updated",
        timestamp: "2024-01-17T14:30:00Z",
        ipAddress: "192.168.1.100",
        userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        location: "New York, USA",
      },
      {
        id: 3,
        action: "Password Changed",
        timestamp: "2023-12-01T10:00:00Z",
        ipAddress: "192.168.1.100",
        userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        location: "New York, USA",
      },
    ],
    sessions: [
      {
        id: 1,
        device: "Windows Desktop",
        browser: "Chrome 120.0",
        location: "New York, USA",
        ipAddress: "192.168.1.100",
        lastActive: "2024-01-18T09:15:00Z",
        current: true,
      },
      {
        id: 2,
        device: "iPhone 15",
        browser: "Safari Mobile",
        location: "New York, USA",
        ipAddress: "192.168.1.101",
        lastActive: "2024-01-17T18:30:00Z",
        current: false,
      },
    ],
  },
  {
    id: 2,
    name: "Sarah Wilson",
    email: "sarah.wilson@example.com",
    mobile: "+1-555-0124",
    gender: "FEMALE",
    status: "ACTIVE",
    profilePic: "/placeholder.svg?height=80&width=80",
    roles: ["Content Manager", "Instructor"],
    createdAt: "2023-02-20T11:45:00Z",
    updatedAt: "2024-01-12T16:10:00Z",
    lastLogin: "2024-01-18T08:45:00Z",
    location: "Los Angeles, USA",
    timezone: "America/Los_Angeles",
    department: "Education Department",
    jobTitle: "Senior Content Manager",
    manager: "Michael Brown",
    employeeId: "EMP002",
    bio: "Creative content manager with 8+ years of experience in educational content development and instructional design.",
    skills: ["Content Strategy", "Instructional Design", "Adobe Creative Suite", "Video Production"],
    socialLinks: {
      linkedin: "https://linkedin.com/in/sarahwilson",
      behance: "https://behance.net/sarahwilson",
    },
    preferences: {
      theme: "light",
      language: "en",
      notifications: {
        email: true,
        push: true,
        sms: false,
      },
    },
    securitySettings: {
      twoFactorEnabled: false,
      lastPasswordChange: "2023-11-15T14:20:00Z",
      loginAttempts: 0,
      accountLocked: false,
    },
    activityLog: [
      {
        id: 1,
        action: "Login",
        timestamp: "2024-01-18T08:45:00Z",
        ipAddress: "192.168.2.100",
        userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
        location: "Los Angeles, USA",
      },
      {
        id: 2,
        action: "Content Created",
        timestamp: "2024-01-17T13:20:00Z",
        ipAddress: "192.168.2.100",
        userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36",
        location: "Los Angeles, USA",
      },
    ],
    sessions: [
      {
        id: 1,
        device: "MacBook Pro",
        browser: "Chrome 120.0",
        location: "Los Angeles, USA",
        ipAddress: "192.168.2.100",
        lastActive: "2024-01-18T08:45:00Z",
        current: true,
      },
    ],
  },
  {
    id: 3,
    name: "Michael Chen",
    email: "michael.chen@example.com",
    mobile: null,
    gender: "MALE",
    status: "INACTIVE",
    profilePic: null,
    roles: ["Student"],
    createdAt: "2023-03-10T09:20:00Z",
    updatedAt: "2023-12-20T10:30:00Z",
    lastLogin: "2023-12-20T10:30:00Z",
    location: "Chicago, USA",
    timezone: "America/Chicago",
    department: null,
    jobTitle: null,
    manager: null,
    employeeId: null,
    bio: "Computer Science student passionate about web development and machine learning.",
    skills: ["Python", "JavaScript", "Machine Learning", "Data Analysis"],
    socialLinks: {
      github: "https://github.com/michaelchen",
    },
    preferences: {
      theme: "dark",
      language: "en",
      notifications: {
        email: false,
        push: false,
        sms: false,
      },
    },
    securitySettings: {
      twoFactorEnabled: false,
      lastPasswordChange: "2023-10-01T12:00:00Z",
      loginAttempts: 0,
      accountLocked: false,
    },
    activityLog: [
      {
        id: 1,
        action: "Login",
        timestamp: "2023-12-20T10:30:00Z",
        ipAddress: "192.168.3.100",
        userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        location: "Chicago, USA",
      },
    ],
    sessions: [],
  },
]

export const mockRolePermissions = [
  {
    roleId: 1,
    roleName: "Administrator",
    permissions: [
      {
        groupName: "User Management",
        privileges: [
          { name: "Create Users", granted: true },
          { name: "Edit Users", granted: true },
          { name: "Delete Users", granted: true },
          { name: "View Users", granted: true },
        ],
      },
      {
        groupName: "Content Management",
        privileges: [
          { name: "Create Content", granted: true },
          { name: "Edit Content", granted: true },
          { name: "Delete Content", granted: true },
          { name: "Publish Content", granted: true },
        ],
      },
      {
        groupName: "System Settings",
        privileges: [
          { name: "Manage Settings", granted: true },
          { name: "View Logs", granted: true },
          { name: "Backup System", granted: true },
        ],
      },
    ],
  },
  {
    roleId: 2,
    roleName: "Content Manager",
    permissions: [
      {
        groupName: "Content Management",
        privileges: [
          { name: "Create Content", granted: true },
          { name: "Edit Content", granted: true },
          { name: "Delete Content", granted: false },
          { name: "Publish Content", granted: true },
        ],
      },
      {
        groupName: "User Management",
        privileges: [
          { name: "View Users", granted: true },
          { name: "Create Users", granted: false },
          { name: "Edit Users", granted: false },
          { name: "Delete Users", granted: false },
        ],
      },
    ],
  },
]
