export const sampleExamPanelData = {
  stats: {
    total: 25,
    completed: 18,
    upcoming: 4,
    live: 1,
    inProgress: 2,
    missed: 0,
    averageScore: 78,
  },
  exams: [
    {
      id: "1",
      name: "JEE Main Mock Test 2024",
      description: "Comprehensive JEE Main mock test covering Physics, Chemistry, and Mathematics with latest pattern.",
      status: "live",
      duration: 180,
      totalQuestions: 90,
      startDate: "2024-01-15T09:00:00Z",
      participants: 1250,
      isHighPriority: true,
    },
    {
      id: "2",
      name: "NEET Biology Practice Test",
      description: "Focused biology practice test for NEET preparation with detailed explanations.",
      status: "upcoming",
      duration: 120,
      totalQuestions: 45,
      startDate: "2024-01-20T14:00:00Z",
      participants: 890,
    },
    {
      id: "3",
      name: "CAT Quantitative Aptitude",
      description: "Quick assessment of quantitative aptitude skills for CAT preparation.",
      status: "in-progress",
      duration: 90,
      totalQuestions: 30,
      startDate: "2024-01-10T10:00:00Z",
      participants: 567,
      progress: {
        answered: 18,
        total: 30,
      },
    },
    {
      id: "4",
      name: "GATE Computer Science Mock",
      description: "Full-length GATE Computer Science mock test with previous year patterns.",
      status: "completed",
      duration: 180,
      totalQuestions: 65,
      startDate: "2024-01-05T09:30:00Z",
      participants: 2100,
      score: 85,
    },
    {
      id: "5",
      name: "SSC CGL Tier 1 Assessment",
      description: "Staff Selection Commission Combined Graduate Level Tier 1 examination.",
      status: "completed",
      duration: 60,
      totalQuestions: 100,
      startDate: "2024-01-01T11:00:00Z",
      participants: 3500,
      score: 72,
    },
  ],
}

export const sampleExamData = {
  id: "1",
  name: "JEE Main Mock Test 2024",
  examCode: "JEE-MOCK-2024-01",
  description: "Comprehensive JEE Main mock test covering Physics, Chemistry, and Mathematics.",
  duration: 180,
  totalQuestions: 90,
  startDate: "2024-01-15T09:00:00Z",
}

export const sampleQuestions = [
  {
    id: "q1",
    questionText: "What is the derivative of sin(x) with respect to x?",
    type: "MCQ",
    marks: 4,
    options: [
      { id: "a", text: "cos(x)" },
      { id: "b", text: "-cos(x)" },
      { id: "c", text: "sin(x)" },
      { id: "d", text: "-sin(x)" },
    ],
  },
  {
    id: "q2",
    questionText: "Calculate the value of ∫₀¹ x² dx",
    type: "NUMERIC",
    marks: 4,
    unit: "units",
  },
  {
    id: "q3",
    questionText: "Which of the following are prime numbers? (Select all that apply)",
    type: "MSQ",
    marks: 4,
    options: [
      { id: "a", text: "17" },
      { id: "b", text: "21" },
      { id: "c", text: "23" },
      { id: "d", text: "25" },
    ],
  },
]

export const sampleResultsData = {
  examName: "JEE Main Mock Test 2024",
  examCode: "JEE-MOCK-2024-01",
  score: 85,
  passingScore: 60,
  rank: 125,
  totalParticipants: 1250,
  percentile: 90,
  correctAnswers: 68,
  totalQuestions: 90,
  timeTaken: "2h 45m",
  totalTime: "3h",
  accuracy: 85,
  sectionResults: [
    {
      name: "Physics",
      score: 82,
      correct: 22,
      wrong: 6,
      timeTaken: "55m",
    },
    {
      name: "Chemistry",
      score: 88,
      correct: 24,
      wrong: 4,
      timeTaken: "50m",
    },
    {
      name: "Mathematics",
      score: 85,
      correct: 22,
      wrong: 6,
      timeTaken: "60m",
    },
  ],
  strengths: [
    "Strong performance in Organic Chemistry",
    "Excellent time management",
    "Good accuracy in Calculus problems",
  ],
  improvements: [
    "Focus more on Physics mechanics",
    "Practice more coordinate geometry",
    "Improve speed in arithmetic calculations",
  ],
  questionAnalysis: [
    {
      questionText: "What is the derivative of sin(x)?",
      status: "correct",
      userAnswer: "cos(x)",
      correctAnswer: "cos(x)",
      explanation: "The derivative of sin(x) is cos(x) by basic differentiation rules.",
      marks: 4,
      timeTaken: "45s",
      difficulty: "Easy",
    },
    {
      questionText: "Calculate the integral of x²",
      status: "wrong",
      userAnswer: "x³",
      correctAnswer: "x³/3 + C",
      explanation: "When integrating x², we add 1 to the power and divide by the new power: x³/3 + C",
      marks: 4,
      timeTaken: "2m 15s",
      difficulty: "Medium",
    },
  ],
  performanceAnalytics: {
    averageTimePerQuestion: "1m 50s",
    fastestQuestion: "30s",
    slowestQuestion: "4m 20s",
    easyAccuracy: 95,
    mediumAccuracy: 80,
    hardAccuracy: 65,
    subjectPerformance: [
      {
        name: "Physics",
        score: 82,
        correct: 22,
        wrong: 6,
        skipped: 2,
      },
      {
        name: "Chemistry",
        score: 88,
        correct: 24,
        wrong: 4,
        skipped: 2,
      },
      {
        name: "Mathematics",
        score: 85,
        correct: 22,
        wrong: 6,
        skipped: 2,
      },
    ],
    insights: {
      strengths: [
        "Consistent performance across all subjects",
        "Good time management skills",
        "Strong conceptual understanding",
      ],
      improvements: [
        "Focus on difficult problems",
        "Reduce calculation errors",
        "Practice more mock tests",
      ],
    },
  },
  comparison: {
    averageScore: 65,
    topScore: 98,
    totalParticipants: 1250,
    passedStudents: 875,
    passPercentage: 70,
    distribution: {
      range90_100: 125,
      range80_89: 250,
      range70_79: 300,
      range60_69: 200,
      range_below_60: 375,
    },
  },
}

export const sampleHistoryData = {
  stats: {
    total: 18,
    completed: 15,
    averageScore: 78,
    bestScore: 95,
  },
  history: [
    {
      id: "1",
      name: "JEE Main Mock Test 2024",
      description: "Comprehensive JEE Main mock test covering Physics, Chemistry, and Mathematics.",
      status: "completed",
      score: 85,
      rank: 125,
      duration: 180,
      completedAt: "2024-01-15T12:00:00Z",
    },
    {
      id: "2",
      name: "NEET Biology Practice Test",
      description: "Focused biology practice test for NEET preparation.",
      status: "completed",
      score: 92,
      rank: 45,
      duration: 120,
      completedAt: "2024-01-10T16:00:00Z",
    },
    {
      id: "3",
      name: "CAT Quantitative Aptitude",
      description: "Quick assessment of quantitative aptitude skills.",
      status: "in-progress",
      duration: 90,
      startedAt: "2024-01-08T10:00:00Z",
    },
  ],
}