const apiConstants = {
    BACKEND_API_BASE_URL: "http://localhost:5000/api/v1",
    TOKEN_KEY: "userToken",
    auth: {
        BASE_ROUTE: "/auth",
        LOGIN: "/auth/login",
        REGISTER: "/auth/register",
        FORGOT_PASSWORD: "/auth/forgot-password",
        VALIDATE_PASSWORD_RESET_LINK: "/validate-reset-link",
        RESET_PASSWORD: "/auth/change-password",
        CURRENT_USER: "/auth/current-user",
        LOGOUT: "/auth/logout",
        AUTHENTICATE: "/authenticate",
    },
    instructors: {
        BASE_ROUTE: "/instructor",
        CREATE_INSTRUCTOR: "/create-instructor",
        UPDATE_INSTRUCTOR: "/update-instructor",
        GET_INSTRUCTOR_DETAILS: "/get-instructor-details",
        DELETE_INSTRUCTOR: "/delete-instructor",
        GET_INSTRUCTOR_STATS: "/get-instructor-stats",
    },
    template: {
        BASE_Route: "/template",
        GET_LIST: "/",
        ADD_TEMPLATE: "/",
    },
    course: {
        BASE_ROUTE: "/course",
        CREATE_COURSE: "/create-course",
        UPDATE_COURSE: "/update-course",
        GET_COURSE_DETAILS: "/get-course-details",
        DELETE_COURSE: "/delete-course",
        GET_COURSE_STATS: "/get-course-stats",
    },
    permissionGroup: {
        BASE_ROUTE: "/privilege-group",
        GET_PERMISSION_GROUP_LIST: "",
        CREATE_PERMISSION_GROUP: "",
        UPDATE_PERMISSION_GROUP: "",
        GET_PERMISSION_GROUP_DETAILS: "",
        DELETE_PERMISSION_GROUP: "",
        GET_PERMISSION_GROUP_STATS: "/get-privilege-group-stats",
    },
    roles: {
        BASE_ROUTE: "/role",
        CREATE_ROLES: "/",
        UPDATE_ROLES: "/",
        GET_ROLES_DETAILS: "/",
        DELETE_ROLES: "/",
        GET_ROLES_STATS: "/get-roles-stats",
        ATTACH_PRIVILEGES: "/attach-privileges",
        ASSIGN_USERS: "/user-role",
    },
    userRoles: {
        BASE_ROUTE: "/user-role",
    },
    permission: {
        BASE_ROUTE: "/privilege",
        CREATE_PERMISSION: "/",
        PERMISSION_LIST: "/",
        UPDATE_PERMISSION: "/",
        GET_PERMISSION_DETAILS: "/",
        DELETE_PERMISSION: "/",
        GET_PERMISSION_STATS: "/get-permission-stats",
    },
    courses: {
        BASE_ROUTE: "/course",
        CREATE_COURSE: "/",
        COURSE_LIST: "/",
        UPDATE_COURSE: "/",
        GET_COURSE_DETAILS: "/",
        DELETE_COURSE: "/",
        GET_COURSE_STATS: "/get-permission-stats",
    },
    module: {
        BASE_ROUTE: "/course",
        CREATE_MODULE: "/",
        MODULE_LIST: "/",
        UPDATE_MODULE: "/",
        GET_MODULE_DETAILS: "/",
        DELETE_MODULE: "/",
        GET_MODULE_STATS: "/get-module-stats",
    },
    lesson: {
        BASE_ROUTE: "/course",
    },
    video: {
        BASE_ROUTE: "/course",
    },
    examPattern: {
        BASE_ROUTE: "/course",
    },
    examBuilder: {
        BASE_ROUTE: "/course",
    },
    question: {
        BASE_ROUTE: "/course",
    },
    routes: {
        BASE_ROUTE: "/route",
        CREATE_ROUTES: "/create-routes",
        UPDATE_ROUTES: "/update-routes",
        GET_ROUTES_DETAILS: "/get-routes-details",
        DELETE_ROUTES: "/delete-routes",
        GET_ROUTES_STATS: "/get-routes-stats",
        DROPDOWN_LIST: "/dropdown",
    },
    users: {
        BASE_ROUTE: "/users",
        CREATE_USERS: "/",
        USERS_LIST: "/",
        UPDATE_USERS: "/",
        GET_USERS_DETAILS: "/",
        DELETE_USERS: "/",
        GET_USERS_STATS: "/get-users-stats",
    },
    loadingStateKeys: {
        CREATE_INSTRUCTOR: "createInstructor",
        UPDATE_INSTRUCTOR: "updateInstructor",
        GET_INSTRUCTOR_DETAILS: "getInstructorDetails",
        GET_INSTRUCTOR_STATS: "getInstructorStats",
        DELETE_INSTRUCTOR: "deleteInstructor",

        CREATE_COURSE: "createCourse",
        UPDATE_COURSE: "updateCourse",
        GET_COURSE_DETAILS: "getCourseDetails",
        GET_COURSE_STATS: "getCourseStats",
        DELETE_COURSE: "deleteCourse",

        CREATE_PERMISSION_GROUP: "createPermissionGroup",
        UPDATE_PERMISSION_GROUP: "updatePermissionGroup",
        GET_PERMISSION_GROUP_DETAILS: "getPermissionGroupDetails",
        GET_PERMISSION_GROUP_STATS: "getPermissionGroupStats",
        GET_PERMISSION_GROUP_LIST: "getPermissionGroupList",
        DELETE_PERMISSION_GROUP: "deletePermissionGroup",

        CREATE_ROLES: "createRoles",
        UPDATE_ROLES: "updateRoles",
        GET_ROLES_DETAILS: "getRolesDetails",
        GET_ROLES_STATS: "getRolesStats",
        DELETE_ROLES: "deleteRoles",
        ATTACH_PERMISSION_ROLES: "attachPermissionsRoles",
        ASSIGN_USERS_ROLES: "assignUsersRoles",

        CREATE_PERMISSION: "createPermission",
        UPDATE_PERMISSION: "updatePermission",
        GET_PERMISSION_DETAILS: "getPermissionDetails",
        GET_PERMISSION_STATS: "getPermissionStats",
        DELETE_PERMISSION: "deletePermission",
        GET_PERMISSION_LIST: "getPermissionsList",

        CREATE_ROUTES: "createRoutes",
        UPDATE_ROUTES: "updateRoutes",
        GET_ROUTES_DETAILS: "getRoutesDetails",
        GET_ROUTES_STATS: "getRoutesStats",
        GET_ROUTES_DROPDOWN: "getRoutesDropdown",
        DELETE_ROUTES: "deleteRoutes",

        CREATE_USERS: "createUsers",
        UPDATE_USERS: "updateUsers",
        GET_USERS_DETAILS: "getUsersDetails",
        GET_USERS_STATS: "getUsersStats",
        DELETE_USERS: "deleteUsers",
        GET_USERS_LIST: "getUsersList",

        SIGN_UP: "signup",
        VERIFY_EMAIL: "verifyEmail",
        SETUP_BASE_INFO: "setupBaseInfo",
        SETUP_PAYMENT: "setupPayment",
        SETUP_DETAILS: "setupDetails",
        SETUP_TEMPLATE: "setupTemplate",
        SETUP_PASSWORD: "setupPassword",
        FILE_UPLOAD_KEY: "fileUpload",
        CURRENT_ONBOARDED_USER: "currentOnboardedUser",
        GET_TEMPLATE_LIST: "getTemplateList",

        AUTHENTICATE: "authenticate",
    },
    theme: {
        LIGHT: "light",
        DARK: "dark",
    },
};
export default apiConstants;
