export const sampleSubscriptionData = {
  id: "sub-premium-001",
  planName: "Premium Monthly",
  planType: "monthly",
  description:
    "Get unlimited access to all courses, premium features, and priority support. Perfect for serious learners who want the complete learning experience.",
  price: 29.99,
  originalPrice: 39.99,
  currency: "USD",
  durationValue: 1,
  durationUnit: "months",
  accessType: "full-course",
  userLimit: null,
  deviceLimit: 3,
  downloadLimit: 50,
  supportLevel: "priority",
  features: [
    "Unlimited Course Access",
    "Downloadable Resources",
    "Priority Support",
    "Certificate of Completion",
    "Mobile App Access",
    "Offline Content",
    "Live Q&A Sessions",
    "Community Access",
  ],
  isActive: true,
  isPopular: true,
  isTrial: false,
  hasCertificate: true,
  trialDuration: null,
  trialUserLimit: null,
  sortOrder: 1,
  maxEnrollments: 1000,
  status: "ACTIVE",
  createdAt: "2025-01-01T10:00:00Z",
  updatedAt: "2025-01-15T14:30:00Z",
}
