const comprehensiveExamPatternData = {
  totalPages: 2,
  totalDocuments: 15,
  records: [
    {
      id: "1",
      name: "Full-Stack Web Development Certification",
      description: "Comprehensive assessment covering HTML, CSS, JavaScript, React, Node.js, and database management. Test your complete web development skills.",
      shuffleQuestions: true,
      shuffleSections: false,
      globalMarkingPolicy: {
        defaultCorrectMark: 2,
        defaultNegativeMark: 0.5,
      },
      sections: [{}, {}, {}, {}], // 4 sections
      securitySettings: {
        enableBrowserLockdown: true,
        disableRightClick: true,
        disableCopyPaste: true,
        preventTabSwitching: true,
        enableAIProctoring: true,
        allowedBrowsers: ["chrome", "firefox"],
        maxTabSwitches: 2,
        suspiciousActivityThreshold: 3,
        enableFullScreenMode: true,
        disableVirtualKeyboard: false,
      },
      accessControlSettings: {
        maxAttempts: 2,
        enableAccessCode: true,
        accessCode: "WEBDEV2024",
        allowedUserGroups: ["premium-students", "certified-learners"],
      },
      attemptRules: {
        maxSectionsToAttempt: 4,
        minSectionsToAttempt: 3,
        allowSectionNavigation: true,
        allowQuestionNavigation: true,
        allowBackNavigation: false,
      },
      resultsSettings: {
        showResultsImmediately: false,
        showCorrectAnswers: true,
        showDetailedAnalysis: true,
        enableResultsDownload: true,
        showRanking: true,
        showPerformanceAnalytics: true,
        enableCertificateGeneration: true,
        passingPercentage: 75,
        enableResultsEmail: true,
        resultVisibilityDelay: 24,
      },
      notificationSettings: {
        enableEmailNotifications: true,
        enableSMSNotifications: true,
        enablePushNotifications: true,
        sendExamReminders: true,
        reminderIntervals: [48, 24, 2],
        sendResultNotifications: true,
        sendStartNotifications: true,
        sendSubmissionConfirmation: true,
        notifyInstructors: true,
        notifyAdmins: true,
      },
      uiConfig: {
        theme: "professional",
        fontSize: "large",
        showTimer: true,
        languageSelector: true,
        accessibleMode: false,
      },
      status: "ACTIVE",
    },
    {
      id: "2",
      name: "JavaScript Fundamentals Quiz",
      description: "Quick assessment of JavaScript basics including variables, functions, arrays, and DOM manipulation.",
      shuffleQuestions: true,
      shuffleSections: true,
      globalMarkingPolicy: {
        defaultCorrectMark: 1,
        defaultNegativeMark: 0.25,
      },
      sections: [{}, {}], // 2 sections
      securitySettings: {
        enableBrowserLockdown: false,
        disableRightClick: false,
        disableCopyPaste: false,
        preventTabSwitching: false,
        enableAIProctoring: false,
        allowedBrowsers: ["chrome", "firefox", "safari"],
        maxTabSwitches: 5,
        suspiciousActivityThreshold: 8,
        enableFullScreenMode: false,
        disableVirtualKeyboard: false,
      },
      accessControlSettings: {
        maxAttempts: 3,
        enableAccessCode: false,
        accessCode: "",
        allowedUserGroups: [],
      },
      attemptRules: {
        maxSectionsToAttempt: 2,
        minSectionsToAttempt: 1,
        allowSectionNavigation: true,
        allowQuestionNavigation: true,
        allowBackNavigation: true,
      },
      resultsSettings: {
        showResultsImmediately: true,
        showCorrectAnswers: true,
        showDetailedAnalysis: false,
        enableResultsDownload: false,
        showRanking: false,
        showPerformanceAnalytics: true,
        enableCertificateGeneration: false,
        passingPercentage: 60,
        enableResultsEmail: false,
        resultVisibilityDelay: 0,
      },
      notificationSettings: {
        enableEmailNotifications: false,
        enableSMSNotifications: false,
        enablePushNotifications: true,
        sendExamReminders: false,
        reminderIntervals: [],
        sendResultNotifications: false,
        sendStartNotifications: false,
        sendSubmissionConfirmation: true,
        notifyInstructors: false,
        notifyAdmins: false,
      },
      uiConfig: {
        theme: "default",
        fontSize: "medium",
        showTimer: true,
        languageSelector: false,
        accessibleMode: false,
      },
      status: "ACTIVE",
    },
    {
      id: "3",
      name: "React Component Architecture",
      description: "Advanced React assessment focusing on component design patterns, hooks, context API, and performance optimization.",
      shuffleQuestions: false,
      shuffleSections: false,
      globalMarkingPolicy: {
        defaultCorrectMark: 3,
        defaultNegativeMark: 1,
      },
      sections: [{}, {}, {}], // 3 sections
      securitySettings: {
        enableBrowserLockdown: true,
        disableRightClick: true,
        disableCopyPaste: true,
        preventTabSwitching: true,
        enableAIProctoring: false,
        allowedBrowsers: ["chrome"],
        maxTabSwitches: 1,
        suspiciousActivityThreshold: 2,
        enableFullScreenMode: true,
        disableVirtualKeyboard: true,
      },
      accessControlSettings: {
        maxAttempts: 1,
        enableAccessCode: true,
        accessCode: "REACT2024",
        allowedUserGroups: ["advanced-developers"],
      },
      attemptRules: {
        maxSectionsToAttempt: 3,
        minSectionsToAttempt: 3,
        allowSectionNavigation: false,
        allowQuestionNavigation: true,
        allowBackNavigation: false,
      },
      resultsSettings: {
        showResultsImmediately: false,
        showCorrectAnswers: false,
        showDetailedAnalysis: true,
        enableResultsDownload: true,
        showRanking: true,
        showPerformanceAnalytics: true,
        enableCertificateGeneration: true,
        passingPercentage: 80,
        enableResultsEmail: true,
        resultVisibilityDelay: 48,
      },
      notificationSettings: {
        enableEmailNotifications: true,
        enableSMSNotifications: false,
        enablePushNotifications: true,
        sendExamReminders: true,
        reminderIntervals: [72, 24],
        sendResultNotifications: true,
        sendStartNotifications: true,
        sendSubmissionConfirmation: true,
        notifyInstructors: true,
        notifyAdmins: true,
      },
      uiConfig: {
        theme: "dark",
        fontSize: "medium",
        showTimer: true,
        languageSelector: false,
        accessibleMode: false,
      },
      status: "DRAFT",
    },
    {
      id: "4",
      name: "Database Design & SQL Mastery",
      description: "Comprehensive database assessment covering normalization, complex queries, indexing, and performance optimization.",
      shuffleQuestions: true,
      shuffleSections: true,
      globalMarkingPolicy: {
        defaultCorrectMark: 2,
        defaultNegativeMark: 0.5,
      },
      sections: [{}, {}, {}, {}, {}], // 5 sections
      securitySettings: {
        enableBrowserLockdown: true,
        disableRightClick: true,
        disableCopyPaste: false,
        preventTabSwitching: true,
        enableAIProctoring: true,
        allowedBrowsers: ["chrome", "firefox"],
        maxTabSwitches: 3,
        suspiciousActivityThreshold: 4,
        enableFullScreenMode: true,
        disableVirtualKeyboard: false,
      },
      accessControlSettings: {
        maxAttempts: 2,
        enableAccessCode: false,
        accessCode: "",
        allowedUserGroups: ["database-students"],
      },
      attemptRules: {
        maxSectionsToAttempt: 5,
        minSectionsToAttempt: 4,
        allowSectionNavigation: true,
        allowQuestionNavigation: true,
        allowBackNavigation: true,
      },
      resultsSettings: {
        showResultsImmediately: true,
        showCorrectAnswers: true,
        showDetailedAnalysis: true,
        enableResultsDownload: true,
        showRanking: false,
        showPerformanceAnalytics: true,
        enableCertificateGeneration: false,
        passingPercentage: 70,
        enableResultsEmail: true,
        resultVisibilityDelay: 0,
      },
      notificationSettings: {
        enableEmailNotifications: true,
        enableSMSNotifications: false,
        enablePushNotifications: true,
        sendExamReminders: true,
        reminderIntervals: [24, 1],
        sendResultNotifications: true,
        sendStartNotifications: true,
        sendSubmissionConfirmation: true,
        notifyInstructors: false,
        notifyAdmins: false,
      },
      uiConfig: {
        theme: "default",
        fontSize: "large",
        showTimer: true,
        languageSelector: true,
        accessibleMode: true,
      },
      status: "ACTIVE",
    },
    {
      id: "5",
      name: "Mobile App Development",
      description: "Cross-platform mobile development test covering React Native, Flutter, and native app deployment strategies.",
      shuffleQuestions: false,
      shuffleSections: true,
      globalMarkingPolicy: {
        defaultCorrectMark: 2.5,
        defaultNegativeMark: 0.75,
      },
      sections: [{}], // 1 section
      securitySettings: {
        enableBrowserLockdown: false,
        disableRightClick: false,
        disablyCopyPaste: false,
        preventTabSwitching: false,
        enableAIProctoring: false,
        allowedBrowsers: ["chrome", "firefox", "safari", "edge"],
        maxTabSwitches: 10,
        suspiciousActivityThreshold: 15,
        enableFullScreenMode: false,
        disableVirtualKeyboard: false,
      },
      accessControlSettings: {
        maxAttempts: 5,
        enableAccessCode: false,
        accessCode: "",
        allowedUserGroups: [],
      },
      attemptRules: {
        maxSectionsToAttempt: 1,
        minSectionsToAttempt: 1,
        allowSectionNavigation: true,
        allowQuestionNavigation: true,
        allowBackNavigation: true,
      },
      resultsSettings: {
        showResultsImmediately: true,
        showCorrectAnswers: false,
        showDetailedAnalysis: false,
        enableResultsDownload: false,
        showRanking: false,
        showPerformanceAnalytics: false,
        enableCertificateGeneration: false,
        passingPercentage: 50,
        enableResultsEmail: false,
        resultVisibilityDelay: 0,
      },
      notificationSettings: {
        enableEmailNotifications: false,
        enableSMSNotifications: false,
        enablePushNotifications: false,
        sendExamReminders: false,
        reminderIntervals: [],
        sendResultNotifications: false,
        sendStartNotifications: false,
        sendSubmissionConfirmation: false,
        notifyInstructors: false,
        notifyAdmins: false,
      },
      uiConfig: {
        theme: "mobile",
        fontSize: "small",
        showTimer: false,
        languageSelector: false,
        accessibleMode: false,
      },
      status: "INACTIVE",
    },
    {
      id: "6",
      name: "Cloud Computing & DevOps",
      description: "Advanced assessment on AWS, Docker, Kubernetes, CI/CD pipelines, and infrastructure as code.",
      shuffleQuestions: true,
      shuffleSections: false,
      globalMarkingPolicy: {
        defaultCorrectMark: 4,
        defaultNegativeMark: 1.5,
      },
      sections: [{}, {}, {}, {}, {}, {}], // 6 sections
      securitySettings: {
        enableBrowserLockdown: true,
        disableRightClick: true,
        disableCopyPaste: true,
        preventTabSwitching: true,
        enableAIProctoring: true,
        allowedBrowsers: ["chrome"],
        maxTabSwitches: 0,
        suspiciousActivityThreshold: 1,
        enableFullScreenMode: true,
        disableVirtualKeyboard: true,
      },
      accessControlSettings: {
        maxAttempts: 1,
        enableAccessCode: true,
        accessCode: "DEVOPS2024",
        allowedUserGroups: ["enterprise-users", "devops-engineers"],
      },
      attemptRules: {
        maxSectionsToAttempt: 6,
        minSectionsToAttempt: 5,
        allowSectionNavigation: false,
        allowQuestionNavigation: false,
        allowBackNavigation: false,
      },
      resultsSettings: {
        showResultsImmediately: false,
        showCorrectAnswers: false,
        showDetailedAnalysis: true,
        enableResultsDownload: true,
        showRanking: true,
        showPerformanceAnalytics: true,
        enableCertificateGeneration: true,
        passingPercentage: 85,
        enableResultsEmail: true,
        resultVisibilityDelay: 72,
      },
      notificationSettings: {
        enableEmailNotifications: true,
        enableSMSNotifications: true,
        enablePushNotifications: true,
        sendExamReminders: true,
        reminderIntervals: [168, 72, 24, 2],
        sendResultNotifications: true,
        sendStartNotifications: true,
        sendSubmissionConfirmation: true,
        notifyInstructors: true,
        notifyAdmins: true,
      },
      uiConfig: {
        theme: "enterprise",
        fontSize: "medium",
        showTimer: true,
        languageSelector: false,
        accessibleMode: false,
      },
      status: "ACTIVE",
    },
    {
      id: "7",
      name: "Python Programming Basics",
      description: "Beginner-friendly Python assessment covering syntax, data structures, functions, and basic object-oriented programming.",
      shuffleQuestions: true,
      shuffleSections: false,
      globalMarkingPolicy: {
        defaultCorrectMark: 1,
        defaultNegativeMark: 0,
      },
      sections: [{}, {}], // 2 sections
      securitySettings: {
        enableBrowserLockdown: false,
        disableRightClick: false,
        disableCopyPaste: false,
        preventTabSwitching: false,
        enableAIProctoring: false,
        allowedBrowsers: ["chrome", "firefox", "safari", "edge"],
        maxTabSwitches: 999,
        suspiciousActivityThreshold: 999,
        enableFullScreenMode: false,
        disableVirtualKeyboard: false,
      },
      accessControlSettings: {
        maxAttempts: 999,
        enableAccessCode: false,
        accessCode: "",
        allowedUserGroups: [],
      },
      attemptRules: {
        maxSectionsToAttempt: 2,
        minSectionsToAttempt: 1,
        allowSectionNavigation: true,
        allowQuestionNavigation: true,
        allowBackNavigation: true,
      },
      resultsSettings: {
        showResultsImmediately: true,
        showCorrectAnswers: true,
        showDetailedAnalysis: true,
        enableResultsDownload: true,
        showRanking: false,
        showPerformanceAnalytics: true,
        enableCertificateGeneration: false,
        passingPercentage: 40,
        enableResultsEmail: false,
        resultVisibilityDelay: 0,
      },
      notificationSettings: {
        enableEmailNotifications: false,
        enableSMSNotifications: false,
        enablePushNotifications: true,
        sendExamReminders: false,
        reminderIntervals: [],
        sendResultNotifications: false,
        sendStartNotifications: false,
        sendSubmissionConfirmation: true,
        notifyInstructors: false,
        notifyAdmins: false,
      },
      uiConfig: {
        theme: "beginner",
        fontSize: "large",
        showTimer: false,
        languageSelector: true,
        accessibleMode: true,
      },
      status: "ACTIVE",
    },
    {
      id: "8",
      name: "Cybersecurity Fundamentals",
      description: "Essential cybersecurity concepts including encryption, network security, threat analysis, and incident response protocols.",
      shuffleQuestions: true,
      shuffleSections: true,
      globalMarkingPolicy: {
        defaultCorrectMark: 3,
        defaultNegativeMark: 1,
      },
      sections: [{}, {}, {}, {}], // 4 sections
      securitySettings: {
        enableBrowserLockdown: true,
        disableRightClick: true,
        disableCopyPaste: true,
        preventTabSwitching: true,
        enableAIProctoring: true,
        allowedBrowsers: ["chrome", "firefox"],
        maxTabSwitches: 1,
        suspiciousActivityThreshold: 2,
        enableFullScreenMode: true,
        disableVirtualKeyboard: false,
      },
      accessControlSettings: {
        maxAttempts: 2,
        enableAccessCode: true,
        accessCode: "SECURITY2024",
        allowedUserGroups: ["security-professionals"],
      },
      attemptRules: {
        maxSectionsToAttempt: 4,
        minSectionsToAttempt: 3,
        allowSectionNavigation: true,
        allowQuestionNavigation: true,
        allowBackNavigation: false,
      },
      resultsSettings: {
        showResultsImmediately: false,
        showCorrectAnswers: false,
        showDetailedAnalysis: true,
        enableResultsDownload: true,
        showRanking: false,
        showPerformanceAnalytics: true,
        enableCertificateGeneration: true,
        passingPercentage: 75,
        enableResultsEmail: true,
        resultVisibilityDelay: 24,
      },
      notificationSettings: {
        enableEmailNotifications: true,
        enableSMSNotifications: false,
        enablePushNotifications: true,
        sendExamReminders: true,
        reminderIntervals: [48, 12],
        sendResultNotifications: true,
        sendStartNotifications: true,
        sendSubmissionConfirmation: true,
        notifyInstructors: true,
        notifyAdmins: true,
      },
      uiConfig: {
        theme: "security",
        fontSize: "medium",
        showTimer: true,
        languageSelector: false,
        accessibleMode: false,
      },
      status: "DRAFT",
    }
  ],
};

export default comprehensiveExamPatternData;