const samplePrivilegeGroupsTableData = {
  totalPages: 2,
  totalDocuments: 8,
  records: [
    {
      id: "1",
      name: "User Management",
      description: "Permissions related to user account management, creation, editing, and deletion of user profiles",
      privilegeCount: 8,
      roleCount: 3,
      isActive: true,
      createdAt: "2024-01-15",
    },
    {
      id: "2",
      name: "Course Management",
      description: "Permissions for creating, editing, and managing educational courses and curriculum content",
      privilegeCount: 12,
      roleCount: 4,
      isActive: true,
      createdAt: "2024-01-20",
    },
    {
      id: "3",
      name: "Content Administration",
      description: "Administrative permissions for managing platform content, media files, and educational resources",
      privilegeCount: 6,
      roleCount: 2,
      isActive: true,
      createdAt: "2024-02-01",
    },
    {
      id: "4",
      name: "System Configuration",
      description: "High-level system configuration and settings management permissions for platform administrators",
      privilegeCount: 15,
      roleCount: 1,
      isActive: true,
      createdAt: "2024-02-10",
    },
    {
      id: "5",
      name: "Reporting & Analytics",
      description: "Access to system reports, analytics dashboards, and data export functionalities",
      privilegeCount: 5,
      roleCount: 3,
      isActive: true,
      createdAt: "2024-02-15",
    },
    {
      id: "6",
      name: "Financial Management",
      description: "Permissions for handling payments, billing, financial reports, and transaction management",
      privilegeCount: 9,
      roleCount: 2,
      isActive: false,
      createdAt: "2024-03-01",
    },
    {
      id: "7",
      name: "Communication Tools",
      description: "Permissions for managing messaging systems, notifications, and communication features",
      privilegeCount: 7,
      roleCount: 4,
      isActive: true,
      createdAt: "2024-03-10",
    },
    {
      id: "8",
      name: "Integration Management",
      description: "Permissions for managing third-party integrations, API access, and external service connections",
      privilegeCount: 4,
      roleCount: 1,
      isActive: true,
      createdAt: "2024-03-15",
    },
  ],
}

export default samplePrivilegeGroupsTableData
